### ISSUE TITLE
ImportError: Missing required dependencies ['numpy']

### ISSUE THREAD

**Issue by jiangweiatgithub** [uber/ludwig#108]
Z:\ludwig>ludwig experiment --data_csv translation.csv --model_definition_file model_definition.yaml
Traceback (most recent call last):
  File "d:\programdata\anaconda3\envs\tensorflow-gpu-1.12\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\programdata\anaconda3\envs\tensorflow-gpu-1.12\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\ProgramData\Anaconda3\envs\tensorflow-gpu-1.12\Scripts\ludwig.exe\__main__.py", line 5, in <module>
  File "d:\programdata\anaconda3\envs\tensorflow-gpu-1.12\lib\site-packages\ludwig\__init__.py", line 16, in <module>
    from ludwig.api import LudwigModel
  File "d:\programdata\anaconda3\envs\tensorflow-gpu-1.12\lib\site-packages\ludwig\api.py", line 35, in <module>
    import pandas as pd
  File "d:\programdata\anaconda3\envs\tensorflow-gpu-1.12\lib\site-packages\pandas\__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']

**Comment by w4nderlust** [comment]
Please follow the installation instructions and install the required packages, numpy is one of them.

**Comment by SachitNayak** [comment]
Hey this issue still pops up! Even though I have double checked the installation of numpy and pandas

**Comment by w4nderlust** [comment]
There's nothing special Ludwig does. It all depends on you python / virtualenv / conda installation.

**Comment by SachitNayak** [comment]
You're right! I'm sorry... I rectified my env and works like a charm now.

**Comment by Karthik1904** [comment]
Hi SachitNayak,
I'm using venv - pandas & numpy are installed but still I'm facing same issue
ImportError: Missing required dependencies ['numpy']

Kindly please tell me the rectification you done on env

**Comment by ifokeev** [comment]
@Karthik1904 check if you have 2 python version inside your venv. Try `which pip` and `which pip3`. If they are different so you're doing something wrong with your package installing.

**Comment by Karthik1904** [comment]
Hi @ifokeev, I tried which pip & which pip3 inside venv. I got below
/var/www/app/app/env/bin/pip
/var/www/app/app/env/bin/pip3

**Comment by ifokeev** [comment]
@Karthik1904 check please how did you install `ludwig`? Using `pip` or `pip3`? Try `which ludwig` also. You have to install in packages dir where packages are searched for on script runtime.
