### ISSUE TITLE
Error when running on text, missing spacy download

### ISSUE THREAD

**Issue by tomgco** [uber/ludwig#146]
When trying to train a model I found that I came across the following error:

```
tomgco@penguin ~/Projects/deep-learning/titanic $ ludwig train -mdf mdf.yaml --data_csv train.csv
Limited tf.compat.v2.summary API due to missing TensorBoard installation
Traceback (most recent call last):
  File "/usr/bin/ludwig", line 11, in <module>
    load_entry_point('ludwig==0.1.0', 'console_scripts', 'ludwig')()
  File "/usr/lib/python3.7/site-packages/ludwig/cli.py", line 86, in main
    CLI()
  File "/usr/lib/python3.7/site-packages/ludwig/cli.py", line 64, in __init__
    getattr(self, args.command)()
  File "/usr/lib/python3.7/site-packages/ludwig/cli.py", line 70, in train
    train.cli(sys.argv[2:])
  File "/usr/lib/python3.7/site-packages/ludwig/train.py", line 663, in cli
    full_train(**vars(args))
  File "/usr/lib/python3.7/site-packages/ludwig/train.py", line 224, in full_train
    random_seed=random_seed
  File "/usr/lib/python3.7/site-packages/ludwig/data/preprocessing.py", line 457, in preprocess_for_training                                                                                                        
    random_seed=random_seed
  File "/usr/lib/python3.7/site-packages/ludwig/data/preprocessing.py", line 62, in build_dataset
    **kwargs
  File "/usr/lib/python3.7/site-packages/ludwig/data/preprocessing.py", line 83, in build_dataset_df
    global_preprocessing_parameters
  File "/usr/lib/python3.7/site-packages/ludwig/data/preprocessing.py", line 124, in build_metadata
    preprocessing_parameters
  File "/usr/lib/python3.7/site-packages/ludwig/features/text_feature.py", line 99, in get_feature_meta
    preprocessing_parameters['lowercase']
  File "/usr/lib/python3.7/site-packages/ludwig/features/text_feature.py", line 80, in feature_meta
    lowercase=lowercase
  File "/usr/lib/python3.7/site-packages/ludwig/utils/strings_utils.py", line 91, in create_vocabulary
    line.lower() if lowercase else line)
  File "/usr/lib/python3.7/site-packages/ludwig/utils/strings_utils.py", line 212, in english_tokenize
    return process_text(text, load_nlp_pipeline())
  File "/usr/lib/python3.7/site-packages/ludwig/utils/nlp_utils.py", line 37, in load_nlp_pipeline
    import en_core_web_sm
ModuleNotFoundError: No module named 'en_core_web_sm'
```

I found that I had to run the following command to ensure it worked `python -m spacy download en_core_web_sm`  Feel free to close this, if it is an environmental issue on my part, but I believe that it is a prerequist step that has been missed in the documentation. Let me know where I can update if it is deemed to be a documentation docs and I will create a PR.

**Comment by tomgco** [comment]
Realised I didn't read the readme fully. https://github.com/uber/ludwig/blame/master/README.md#L65
