### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by jiangweiatgithub** [uber/ludwig#147]
F:\ezjoiner>ludwig experiment --data_csv eng_incomplete_full.csv --model_definit
ion_file sent_complete_model_definition.yaml
f:\programdata\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: C
onversion of the second argument of issubdtype from `float` to `np.floating` is
deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type
`.
  from ._conv import register_converters as _register_converters
 _         _        _
| |_  _ __| |_ __ _(_)__ _
| | || / _` \ V  V / / _` |
|_|\_,_\__,_|\_/\_/|_\__, |
                     |___/
ludwig v0.1.0 - Experiment

Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)
  File "f:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\ProgramData\Anaconda3\Scripts\ludwig.exe\__main__.py", line 9, in <mo
dule>
  File "f:\programdata\anaconda3\lib\site-packages\ludwig\cli.py", line 86, in m
ain
    CLI()
  File "f:\programdata\anaconda3\lib\site-packages\ludwig\cli.py", line 64, in _
_init__
    getattr(self, args.command)()
  File "f:\programdata\anaconda3\lib\site-packages\ludwig\cli.py", line 67, in e
xperiment
    experiment.cli(sys.argv[2:])
  File "f:\programdata\anaconda3\lib\site-packages\ludwig\experiment.py", line 5
48, in cli
    experiment(**vars(args))
  File "f:\programdata\anaconda3\lib\site-packages\ludwig\experiment.py", line 2
01, in experiment
    random_seed
  File "f:\programdata\anaconda3\lib\site-packages\ludwig\utils\misc.py", line 4
3, in get_experiment_description
    stdout=open(os.devnull, 'w')) == 0
  File "f:\programdata\anaconda3\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "f:\programdata\anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "f:\programdata\anaconda3\lib\subprocess.py", line 997, in _execute_child

    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by jiangweiatgithub** [comment]
Just found the solution:
https://blog.csdn.net/u012436149/article/details/72865908

That is, add the path to git to the system environment variable PATH. :-)
