### ISSUE TITLE
model.train(data_df=data) - The system cannot find the file specified

### ISSUE THREAD

**Issue by nau7ic** [uber/ludwig#172]
Thank for developing such a great program :)

I installed ludwig via pip

Here is my Code:

from ludwig import LudwigModel
import pandas as pd
import yaml

data = pd.read_csv('C:\Workspaces\Python\ludwig\system1.csv')
print(data.head())

model_definition = yaml.load('{input_features: [{name: X1, type: numerical}, {name: X2, type: numerical}, {name: X3, type: numerical}, {name: X4, type: numerical}], output_features: [{name: OUT, type: numerical}]}')
print(model_definition)
model = LudwigModel(model_definition)
train_stats = model.train(data_df=data)

That is the Output of my code
------------------------------------------------------------------------------------------------------------

  X1;X2;X3;X4;OUT
0  0.493969232;0.015396403;-0.165187229;-0.120615...
1  0.475143579;0.181427819;1.225261361;-0.4971284...
2  0.474704679;0.367516287;0.817723039;-0.5059064...
3  0.442694568;0.531490347;-0.994455752;-1.146108...
4  0.499078571;0.214648806;-0.783806151;-0.018428...

{'input_features': [{'name': 'X1', 'type': 'numerical'}, {'name': 'X2', 'type': 'numerical'}, {'name': 'X3', 'type': 'numerical'}, {'name': 'X4', 'type': 'numerical'}], 'output_features': [{'name': 'OUT', 'type': 'numerical'}]}

Traceback (most recent call last):
  File "c:\Users\User\.vscode\extensions\ms-python.python-2019.2.5433\pythonFiles\ptvsd_launcher.py", line 45, in <module>
    main(ptvsdArgs)
  File "c:\Users\User\.vscode\extensions\ms-python.python-2019.2.5433\pythonFiles\lib\python\ptvsd\__main__.py", line 357, in main
    run()
  File "c:\Users\User\.vscode\extensions\ms-python.python-2019.2.5433\pythonFiles\lib\python\ptvsd\__main__.py", line 257, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Program Files\Python36\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Program Files\Python36\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Program Files\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Workspaces\Python\ludwig\try.py", line 11, in <module>
    train_stats = model.train(data_df=data)
  File "C:\Program Files\Python36\lib\site-packages\ludwig\api.py", line 417, in train
    random_seed=random_seed)
  File "C:\Program Files\Python36\lib\site-packages\ludwig\utils\misc.py", line 43, in get_experiment_description
    stdout=open(os.devnull, 'w')) == 0
  File "C:\Program Files\Python36\lib\subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Program Files\Python36\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python36\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by w4nderlust** [comment]
Please use the code from master it already solves this issue. Thanks.
