### ISSUE TITLE
[Question] I am unable to predict using my model

### ISSUE THREAD

**Issue by Riz-waan** [uber/ludwig#192]
When I try to run my model I get this:

```
 _         _        _      
| |_  _ __| |_ __ _(_)__ _ 
| | || / _` \ V  V / / _` |
|_|\_,_\__,_|\_/\_/|_\__, |
                     |___/ 
ludwig v0.1.0 - Predict

Dataset type: generic
Dataset path: testdata.csv
Model path: /content/gdrive/My Drive/Colab Files/Ludwig Siraj Chatbot/model/experiment_run_2/model
Output path: results

Loading metadata from: /content/gdrive/My Drive/Colab Files/Ludwig Siraj Chatbot/model/experiment_run_2/model/train_set_metadata.json
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 2656, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'user1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ludwig", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/ludwig/cli.py", line 86, in main
    CLI()
  File "/usr/local/lib/python3.6/dist-packages/ludwig/cli.py", line 64, in __init__
    getattr(self, args.command)()
  File "/usr/local/lib/python3.6/dist-packages/ludwig/cli.py", line 73, in predict
    predict.cli(sys.argv[2:])
  File "/usr/local/lib/python3.6/dist-packages/ludwig/predict.py", line 379, in cli
    full_predict(**vars(args))
  File "/usr/local/lib/python3.6/dist-packages/ludwig/predict.py", line 86, in full_predict
    only_predictions
  File "/usr/local/lib/python3.6/dist-packages/ludwig/data/preprocessing.py", line 684, in preprocess_for_prediction
    train_set_metadata=train_set_metadata
  File "/usr/local/lib/python3.6/dist-packages/ludwig/data/preprocessing.py", line 61, in build_dataset
    **kwargs
  File "/usr/local/lib/python3.6/dist-packages/ludwig/data/preprocessing.py", line 89, in build_dataset_df
    global_preprocessing_parameters
  File "/usr/local/lib/python3.6/dist-packages/ludwig/data/preprocessing.py", line 152, in build_data
    preprocessing_parameters
  File "/usr/local/lib/python3.6/dist-packages/ludwig/data/preprocessing.py", line 173, in handle_missing_values
    dataset_df[feature['name']] = dataset_df[feature['name']].fillna(
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 2658, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'user1'
```

What does KeyError mean?

**Comment by Riz-waan** [comment]
Also let me know what info you want me to attach for debugging.

**Comment by JacobBruce** [comment]
I'm having the same issue, I'm on a Windows machine. It doesn't seem to seem to matter what type of input features I use, I've tried time series and text encoders and both give the same error.

**Comment by Riz-waan** [comment]
Did you find a solution?

**Comment by JacobBruce** [comment]
Yeah, it seems like the inputs and outputs must have the same name in both your csv data file and your yaml definition file.

**Comment by Riz-waan** [comment]
Example please?

**Comment by JacobBruce** [comment]
Model file:

```
input_features:
    -
        name: "TextIn"
        type: text

output_features:
    -
        name: "NumOut"
        type: numerical

training:
        epochs: 100
```

training data csv:

```
TextIn,NumOut
"input text data",0.1643
...
```

**Comment by MinderBender** [comment]
You don't need quotes in the feature names. Try:

```yaml
input_features:
    -
        name: TextIn
        type: text

output_features:
    -
        name: NumOut
        type: numerical

training:
        epochs: 100

**Comment by w4nderlust** [comment]
Yes the fact that the model definition names are the same names of the columns in your data (both when training and when predicting) is basically the only assumption that Ludwig makes. If you respect that, it should work right away.
So in the case of @Riz-waan , if your model definition was copied from the examples, with `user1` and `user2` as names of input and output feature respectively, both your training data csv and your test data csv must contain columns with those names (or you can change the `name` entries in your model definition with the names of the columns in your data).
In the case of @JacobBruce , if you trained with a text column named `test`, the same column needs to be present in your test data too.
Closing this, let me know if you have further questions.

**Comment by Riz-waan** [comment]
So in my prediction set I need to have user1 and user2? Instead of just user1?

On Mar 11, 2019 2:04 AM, Piero Molino <notifications@github.com> wrote:

Yes the fact that the model definition names are the same names of the columns in your data (both when training and when predicting) is basically the only assumption that Ludwig makes. If you respect that, it should work right away.
So in the case of @Riz-waan<https://github.com/Riz-waan> , if your model definition was copied from the examples, with user1 and user2 as names of input and output feature respectively, both your training data csv and your test data csv must contain columns with those names (or you can change the name entries in your model definition with the names of the columns in your data).
In the case of @JacobBruce<https://github.com/JacobBruce> , if you trained with a text column named test, the same column needs to be present in your test data too.
Closing this, let me know if you have further questions.

**Comment by w4nderlust** [comment]
If you use `--only_predictions` and only want the predictions, you only need `user1`, if you also want to compute the quality of your predictions you need something to compare the predictions agaings, so you would need `user2` too in this case.
