### ISSUE TITLE
TypeError with multiple image input features

### ISSUE THREAD

**Issue by JacobBruce** [uber/ludwig#209]
One image input feature seem to work fine but if I try to create model with more than one image inputs I get the following error. I'm on Windows 10 and using the latest version of ludwig.
```
Building dataset (it may take a while)
Traceback (most recent call last):
  File "C:\Users\JD\AppData\Local\Programs\Python\Python36\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\JD\AppData\Local\Programs\Python\Python36\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\venv\Scripts\ludwig.exe\__main__.py", line 9, in <module>
  File "c:\venv\lib\site-packages\ludwig\cli.py", line 86, in main
    CLI()
  File "c:\venv\lib\site-packages\ludwig\cli.py", line 64, in __init__
    getattr(self, args.command)()
  File "c:\venv\lib\site-packages\ludwig\cli.py", line 70, in train
    train.cli(sys.argv[2:])
  File "c:\venv\lib\site-packages\ludwig\train.py", line 729, in cli
    full_train(**vars(args))
  File "c:\venv\lib\site-packages\ludwig\train.py", line 243, in full_train
    random_seed=random_seed
  File "c:\venv\lib\site-packages\ludwig\data\preprocessing.py", line 458, in preprocess_for_training
    random_seed=random_seed
  File "c:\venv\lib\site-packages\ludwig\data\preprocessing.py", line 61, in build_dataset
    **kwargs
  File "c:\venv\lib\site-packages\ludwig\data\preprocessing.py", line 89, in build_dataset_df
    global_preprocessing_parameters
  File "c:\venv\lib\site-packages\ludwig\data\preprocessing.py", line 164, in build_data
    preprocessing_parameters
  File "c:\venv\lib\site-packages\ludwig\features\image_feature.py", line 136, in add_feature_data
    data[feature['name']][i, :, :, :] = img
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by msaisumanth** [comment]
@JacobBruce This identified and fixed this bug yesterday. Please fetch the latest code from master and rebuild Ludwig.
