### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'git': 'git'

### ISSUE THREAD

**Issue by xuean009** [uber/ludwig#233]
| |_  _ __| |_ __ _(_)__ _
| | || / _` \ V  V / / _` |
|_|\_,_\__,_|\_/\_/|_\__, |
                     |___/
ludwig v0.1.0 - Train

Traceback (most recent call last):
  File "/home/gpu/.conda/envs/ludwig/bin/ludwig", line 10, in <module>
    sys.exit(main())
  File "/home/gpu/.conda/envs/ludwig/lib/python3.6/site-packages/ludwig/cli.py", line 86, in main
    CLI()
  File "/home/gpu/.conda/envs/ludwig/lib/python3.6/site-packages/ludwig/cli.py", line 64, in __init__
    getattr(self, args.command)()
  File "/home/gpu/.conda/envs/ludwig/lib/python3.6/site-packages/ludwig/cli.py", line 70, in train
    train.cli(sys.argv[2:])
  File "/home/gpu/.conda/envs/ludwig/lib/python3.6/site-packages/ludwig/train.py", line 663, in cli
    full_train(**vars(args))
  File "/home/gpu/.conda/envs/ludwig/lib/python3.6/site-packages/ludwig/train.py", line 192, in full_train
    random_seed
  File "/home/gpu/.conda/envs/ludwig/lib/python3.6/site-packages/ludwig/utils/misc.py", line 43, in get_experiment_description
    stdout=open(os.devnull, 'w')) == 0
  File "/home/gpu/.conda/envs/ludwig/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/gpu/.conda/envs/ludwig/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/home/gpu/.conda/envs/ludwig/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git': 'git'

**Comment by w4nderlust** [comment]
Already solved, use the code in master

**Comment by xuean009** [comment]
> Already solved, use the code in master

Sorry, I don't understand very well. Can you give me a detailed explanation? Thank you

**Comment by w4nderlust** [comment]
If you pull the code from the master branch and install it, you will not encounter this issue anymore because it has been already solved, but if you installed from pip the version you installed (v0.1.1) does not contain the fix, it will be available in the next release (v0.1.1).
