### ISSUE TITLE
KeyError: 'target'

### ISSUE THREAD

**Issue by s1223** [uber/ludwig#281]
I can train but error while predict 

I was install ludwig with "pip install ludwig"
and I was install Ludwig's requirements  
1. numpy
2. pandas
3. scipy
4. scikit-learn
5. scikit-image
6. spacy
7. tensorflow
8. matplotlib
9. seaborn
10. Cython
11. h5py
12. tqdm
13. tabulate
14. PyYAML

my OS : Windows 10
Python 3.6.8 :: Anaconda, Inc.

but when I predict with "ludwig predict --data_csv C:\Users\user\Desktop\heart1.csv --model_path C:\Users\user\results\experiment_run_5\model"

and will be error like this 

if you can help with this problem please help me to find the solution, thank you.

I train the model with "ludwig train --data_csv C:\Users\fian\Desktop\heart.csv --model_definition "{input_features: [{name: age, type: text}], output_features: [{name: target, type: category}]}" "

my data (csv and model): 
[sample.zip](https://github.com/uber/ludwig/files/3064283/sample.zip)

(base) C:\Users\user>ludwig predict --data_csv C:\Users\user\Desktop\heart1.csv --model_path C:\Users\user\results\experiment_run_5\model

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

c:\users\user\anaconda3\lib\site-packages\ipykernel\kernelbase.py:19: VisibleDeprecationWarning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
    Install tornado itself to use zmq with the tornado IOLoop.

  from jupyter_client.session import utcnow as now
 _         _        _
| |_  _ __| |_ __ _(_)__ _
| | || / _` \ V  V / / _` |
|_|\_,_\__,_|\_/\_/|_\__, |
                     |___/
ludwig v0.1.1 - Predict

Dataset type: generic
Dataset path: C:\Users\user\Desktop\heart1.csv
Model path: C:\Users\user\results\experiment_run_5\model
Output path: results_0

Loading metadata from: C:\Users\user\results\experiment_run_5\model\train_set_metadata.json
Traceback (most recent call last):
  File "c:\users\user\anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2657, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'target'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\Anaconda3\Scripts\ludwig.exe\__main__.py", line 9, in <module>
  File "c:\users\user\anaconda3\lib\site-packages\ludwig\cli.py", line 93, in main
    CLI()
  File "c:\users\user\anaconda3\lib\site-packages\ludwig\cli.py", line 65, in __init__
    getattr(self, args.command)()
  File "c:\users\user\anaconda3\lib\site-packages\ludwig\cli.py", line 77, in predict
    predict.cli(sys.argv[2:])
  File "c:\users\user\anaconda3\lib\site-packages\ludwig\predict.py", line 379, in cli
    full_predict(**vars(args))
  File "c:\users\user\anaconda3\lib\site-packages\ludwig\predict.py", line 86, in full_predict
    only_predictions
  File "c:\users\user\anaconda3\lib\site-packages\ludwig\data\preprocessing.py", line 695, in preprocess_for_prediction
    train_set_metadata=train_set_metadata
  File "c:\users\user\anaconda3\lib\site-packages\ludwig\data\preprocessing.py", line 61, in build_dataset
    **kwargs
  File "c:\users\user\anaconda3\lib\site-packages\ludwig\data\preprocessing.py", line 89, in build_dataset_df
    global_preprocessing_parameters
  File "c:\users\user\anaconda3\lib\site-packages\ludwig\data\preprocessing.py", line 152, in build_data
    preprocessing_parameters
  File "c:\users\user\anaconda3\lib\site-packages\ludwig\data\preprocessing.py", line 173, in handle_missing_values
    dataset_df[feature['name']] = dataset_df[feature['name']].fillna(
  File "c:\users\user\anaconda3\lib\site-packages\pandas\core\frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "c:\users\user\anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'target'**Describe the bug**

**To Reproduce**

Please provide code, yaml definition file and a sample of data in order to entirely reproduce the issue.
Issues that are not reproducible will be ignored.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- Python version
- Ludwig version

**Additional context**

**Comment by gobzer** [comment]
Add 'target' header to heart1.csv
**heart1.csv**
```
age,target
17
18
```

**Comment by w4nderlust** [comment]
Use the `--only_predictions` flag when predicting.
