### ISSUE TITLE
Cannot reproduce NLU example from the website

### ISSUE THREAD

**Issue by shrinivaskallol** [uber/ludwig#283]
**Describe the bug**
Cannot reproduce the Natural language understanding result with the data and the model definition file displayed on the website in Ludwig>examples>Natural language understanding
**To Reproduce**
model_definition = {}
model_definition['input_features'] = [{'name': 'utterance', 'type': 'text', 'level':'word','encoder':'rnn','cell_type': 'lstm',
                                        'bidirectional': 'true','num_layers': 2,'reduce_output': 'none'}
                                     ]

model_definition['output_features'] = [{'name': 'intent', 'type': 'category', 'reduce_input': 'sum',
                                        'num_fc_layers': 1,'fc_size': 64},
                                      {'name':'slots','type':'sequence', 'decoder':'tagger'}]

model_definition['preprocessing'] = { 'sequence': {   'fill_value': '',
                                         'format': 'space',
                                         'lowercase': False,
                                         'missing_value_strategy': 'fill_with_const',
                                         'most_common': 20000,
                                         'padding': 'left',
                                         'padding_symbol': '<PAD>',
                                         'sequence_length_limit': 256,
                                         'unknown_symbol': '<UNK>'},
                                     
                                         'text': {'char_format': 'characters',
                                         'char_most_common': 70,
                                         'char_sequence_length_limit': 1024,
                                         'fill_value': '',
                                         'lowercase': True,
                                         'missing_value_strategy': 'fill_with_const',
                                         'padding': 'right',
                                         'padding_symbol': '<PAD>',
                                         'unknown_symbol': '<UNK>',
                                         'word_format': 'space',
                                         'word_most_common': 20000,
                                         'word_sequence_length_limit': 256}}

data = pd.DataFrame({'utterance': ['I want a pizza','Book a flight to Boston','Book a flight at 7pm to London'],
                   'intent': ['order_food','book_flight','book_flight'],
                   'slots':['O O O B-Food_type','O O O O B-City', 'O O O O B-Departure_time O B-City']})

model = ludwig.LudwigModel(model_definition)

trained_model = model.train(data_df=data, random_seed=42)

ERROR MESSAGE:
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1333     try:
-> 1334       return fn(*args)
   1335     except errors.OpError as e:

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1318       return self._call_tf_sessionrun(
-> 1319           options, feed_dict, fetch_list, target_list, run_metadata)
   1320 

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1406         self._session, options, feed_dict, fetch_list, target_list,
-> 1407         run_metadata)
   1408 

InvalidArgumentError: Paddings must be non-negative: 0 -1
	 [[{{node slots/loss_slots/Pad}}]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-45-b0a795ad9640> in <module>
----> 1 trained_model = model.train(data_df=data, random_seed=42)

~/anaconda3/lib/python3.7/site-packages/ludwig/api.py in train(self, data_df, data_train_df, data_validation_df, data_test_df, data_csv, data_train_csv, data_validation_csv, data_test_csv, data_hdf5, data_train_hdf5, data_validation_hdf5, data_test_hdf5, train_set_metadata_json, dataset_type, model_name, model_load_path, model_resume_path, skip_save_model, skip_save_progress, skip_save_log, skip_save_processed_input, output_directory, gpus, gpu_fraction, random_seed, logging_level, debug, **kwargs)
    516             gpu_fraction=gpu_fraction,
    517             random_seed=random_seed,
--> 518             debug=debug
    519         )
    520 

~/anaconda3/lib/python3.7/site-packages/ludwig/train.py in train(training_set, validation_set, test_set, model_definition, save_path, model_load_path, resume, skip_save_model, skip_save_progress, skip_save_log, gpus, gpu_fraction, use_horovod, random_seed, debug)
    428         gpus=gpus, gpu_fraction=gpu_fraction,
    429         random_seed=random_seed,
--> 430         **model_definition['training']
    431     )
    432 

~/anaconda3/lib/python3.7/site-packages/ludwig/models/model.py in train(self, training_set, validation_set, test_set, validation_field, validation_measure, save_path, regularization_lambda, epochs, learning_rate, batch_size, eval_batch_size, bucketing_field, dropout_rate, early_stop, reduce_learning_rate_on_plateau, reduce_learning_rate_on_plateau_patience, reduce_learning_rate_on_plateau_rate, increase_batch_size_on_plateau, increase_batch_size_on_plateau_patience, increase_batch_size_on_plateau_rate, increase_batch_size_on_plateau_max, learning_rate_warmup_epochs, resume, skip_save_model, skip_save_progress, skip_save_log, gpus, gpu_fraction, random_seed, **kwargs)
    519                         learning_rate=current_learning_rate,
    520                         dropout_rate=dropout_rate,
--> 521                         is_training=True
    522                     )
    523                 )

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    927     try:
    928       result = self._run(None, fetches, feed_dict, options_ptr,
--> 929                          run_metadata_ptr)
    930       if run_metadata:
    931         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1150     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1151       results = self._do_run(handle, final_targets, final_fetches,
-> 1152                              feed_dict_tensor, options, run_metadata)
   1153     else:
   1154       results = []

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1326     if handle is None:
   1327       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1328                            run_metadata)
   1329     else:
   1330       return self._do_call(_prun_fn, handle, feeds, fetches)

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1346           pass
   1347       message = error_interpolation.interpolate(message, self._graph)
-> 1348       raise type(e)(node_def, op, message)
   1349 
   1350   def _extend_graph(self):

InvalidArgumentError: Paddings must be non-negative: 0 -1
	 [[node slots/loss_slots/Pad (defined at /Users/shrinivas/anaconda3/lib/python3.7/site-packages/ludwig/models/modules/loss_modules.py:66) ]]

Caused by op 'slots/loss_slots/Pad', defined at:
  File "/Users/shrinivas/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/shrinivas/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 505, in start
    self.io_loop.start()
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/Users/shrinivas/anaconda3/lib/python3.7/asyncio/base_events.py", line 528, in run_forever
    self._run_once()
  File "/Users/shrinivas/anaconda3/lib/python3.7/asyncio/base_events.py", line 1764, in _run_once
    handle._run()
  File "/Users/shrinivas/anaconda3/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 1233, in inner
    self.run()
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2819, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2845, in _run_cell
    return runner(coro)
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3020, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3185, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-45-b0a795ad9640>", line 1, in <module>
    trained_model = model.train(data_df=data, random_seed=42)
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/ludwig/api.py", line 518, in train
    debug=debug
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/ludwig/train.py", line 413, in train
    debug=debug
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/ludwig/models/model.py", line 109, in __init__
    **kwargs
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/ludwig/models/model.py", line 183, in __build
    is_training=self.is_training
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/ludwig/models/outputs.py", line 43, in build_outputs
    **kwargs
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/ludwig/models/outputs.py", line 93, in build_single_output
    **kwargs
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/ludwig/features/base_feature.py", line 314, in concat_dependencies_and_build_output
    **kwargs
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/ludwig/features/sequence_feature.py", line 250, in build_output
    kwarg=kwargs
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/ludwig/features/sequence_feature.py", line 299, in build_sequence_output
    class_biases
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/ludwig/features/sequence_feature.py", line 497, in sequence_loss
    eval_logits
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/ludwig/models/modules/loss_modules.py", line 66, in seq2seq_sequence_loss
    padded_logits = tf.pad(logits, [[0, 0], [0, difference], [0, 0]])
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 2299, in pad
    result = gen_array_ops.pad(tensor, paddings, name=name)
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 5539, in pad
    "Pad", input=input, paddings=paddings, name=name)
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/Users/shrinivas/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Paddings must be non-negative: 0 -1
	 [[node slots/loss_slots/Pad (defined at /Users/shrinivas/anaconda3/lib/python3.7/site-packages/ludwig/models/modules/loss_modules.py:66) ]]
**Expected behavior**
trained model and multivariate prediction

**Screenshots**

**Environment (please complete the following information):**
- Python version 3.7.1
- Ludwig version 0.1.1

**Additional context**

**Comment by w4nderlust** [comment]
Thanks for providing this. I pushed a commit that solves the issue (the `word_format was not used, english_tokenizer was used instead). Closing this, feel free to comment again if the error persists.
