### ISSUE TITLE
Web service wrapper around ludwig

### ISSUE THREAD

**Issue by bertyhell** [uber/ludwig#286]
I'm trying to make ludwig more accessable from other languages by wrapping it in a webservice (cherrypy)

When i try to make a call to the webservice to train a model i get the error:
```
 signal only works in main thread
```

I'm looking for some context around how these signals are used inside ludwig. I assume this could be resolved by starting ludwig in a separate process and then setup a socket connection between the ludwig process and the cherrypy web service.

This is the relevant code i have so far:

**service in cherrypy:**
```python
class AiWebService(object):

    @cherrypy.expose
    @cherrypy.tools.json_in()
    @cherrypy.tools.json_out()
    def train(self):
        data = cherrypy.request.json
        if 'training_samples' not in data:
            return RecursiveError('"training_samples" property is required on body to begin training').to_json()
        if 'definitions' not in data:
            return RecursiveError('"definitions" property is required on body to begin training').to_json()

        training_samples = pd.DataFrame(data.get('training_samples'))
        definitions = data.get('definitions')
        output = p.train(training_samples, definitions)
        return output

if __name__ == '__main__':
    cherrypy.config.update({'server.socket_host': '0.0.0.0'})
    cherrypy.quickstart(AiWebService())
```
https://gitlab.com/bertyhell/woody-puzzle-solver/blob/master/src/server/ludwigproxy.py

**wrapper around the ludwig api:**
```python
    def train(self, training_samples, model_definitions):
        model = LudwigModel(model_definitions)
        train_stats = model.train(training_samples)
        return {'message': 'ok'}
```
https://gitlab.com/bertyhell/woody-puzzle-solver/blob/master/src/server/service.py

**full error:**
```
ERROR:cherrypy.error.2203522445776:[14/Apr/2019:11:34:47] HTTP 
Traceback (most recent call last):
  File "C:\Users\verhe\AppData\Local\Programs\Python\Python36\lib\site-packages\cherrypy\_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "C:\Users\verhe\AppData\Local\Programs\Python\Python36\lib\site-packages\cherrypy\_cprequest.py", line 687, in _do_respond
    response.body = self.handler()
  File "C:\Users\verhe\AppData\Local\Programs\Python\Python36\lib\site-packages\cherrypy\lib\encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Users\verhe\AppData\Local\Programs\Python\Python36\lib\site-packages\cherrypy\lib\jsontools.py", line 59, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "C:\Users\verhe\AppData\Local\Programs\Python\Python36\lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:/Users/verhe/Documents/storied/repos/woody-puzzle-solver/src/server/service.py", line 26, in train
    output = p.train(training_samples, definitions)
  File "C:\Users\verhe\Documents\storied\repos\woody-puzzle-solver\src\server\ludwigproxy.py", line 7, in train
    train_stats = model.train(training_samples)
  File "C:\Users\verhe\AppData\Local\Programs\Python\Python36\lib\site-packages\ludwig\api.py", line 494, in train
    debug=debug
  File "C:\Users\verhe\AppData\Local\Programs\Python\Python36\lib\site-packages\ludwig\train.py", line 383, in train
    **model_definition['training']
  File "C:\Users\verhe\AppData\Local\Programs\Python\Python36\lib\site-packages\ludwig\models\model.py", line 363, in train
    signal.signal(signal.SIGINT, self.set_epochs_to_1_or_quit)
  File "C:\Users\verhe\AppData\Local\Programs\Python\Python36\lib\signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
```

**Comment by w4nderlust** [comment]
Ludwig uses signals in [model.py](https://github.com/uber/ludwig/blob/master/ludwig/models/model.py#L387) for allowing the user to interrupt training and still completing the process.
Not sure what causes the problem with cherrypy, I guess it doesn't like the use of signal, probably because it manages signals itself.
I would suggest to try to pull the code from master, and add a check `threading.current_thread() == threading.main_thread()` as suggested in this [StackOverflow question](https://stackoverflow.com/questions/23206787/check-if-current-thread-is-main-thread-in-python) before importing signal and before line 387 in model.py.
Let me know if it works because in case you can do a PR or I can add it myself.

**Comment by bertyhell** [comment]
@w4nderlust Yes, that fixed it
Thank you for the clear indications on where to look

I love the package btw. The documentation is great :D

**Comment by w4nderlust** [comment]
Thanks! You are welcome. Closing this.
Let me know if you are considering doing a PR for the cherrypy server itself, it would be useful to many users!
