### ISSUE TITLE
KeyError: 'type'

### ISSUE THREAD

**Issue by MachineLearningNewbie** [uber/ludwig#304]
Not sure if this is necessarily a bug, but I keep running into this issue and wanted to see if anyone on here had any idea on why it keeps occurring.

**To Reproduce**

### **Input:**
ludwig experiment --data_csv C:\Users\name\Downloads\20140306_20190305_EOD\AAPL.csv --model_definition "{input_features: [{name: date, type:timeseries}], output_features: [{name:close, type:numerical}]}"

### **Output:**
WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

c:\users\name\appdata\local\programs\python\python37\lib\argparse.py:2402: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  result = type_func(arg_string)
 _         _        _
| |_  _ __| |_ __ _(_)__ _
| | || / _` \ V  V / / _` |
|_|\_,_\__,_|\_/\_/|_\__, |
                     |___/
ludwig v0.1.1 - Experiment

Traceback (most recent call last):
  File "c:\users\name\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\name\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\name\AppData\Local\Programs\Python\Python37\Scripts\ludwig.exe\__main__.py", line 9, in <module>
  File "c:\users\name\appdata\local\programs\python\python37\lib\site-packages\ludwig\cli.py", line 94, in main
    CLI()
  File "c:\users\name\appdata\local\programs\python\python37\lib\site-packages\ludwig\cli.py", line 60, in __init__
    getattr(self, args.command)()
  File "c:\users\name\appdata\local\programs\python\python37\lib\site-packages\ludwig\cli.py", line 65, in experiment
    experiment.cli(sys.argv[2:])
  File "c:\users\name\appdata\local\programs\python\python37\lib\site-packages\ludwig\experiment.py", line 466, in cli
    experiment(**vars(args))
  File "c:\users\name\appdata\local\programs\python\python37\lib\site-packages\ludwig\experiment.py", line 194, in experiment
    **kwargs
  File "c:\users\name\appdata\local\programs\python\python37\lib\site-packages\ludwig\train.py", line 181, in full_train
    model_definition = merge_with_defaults(model_definition)
  File "c:\users\name\appdata\local\programs\python\python37\lib\site-packages\ludwig\utils\defaults.py", line 217, in merge_with_defaults
    'type']].default_validation_measure
KeyError: 'type'

### **File Used:**
[APPL file in zip](https://drive.google.com/file/d/1ElC_Jsc4ZAq8CNXQgx23OmhVFeaPZXd3/view?usp=sharing)

**Environment (please complete the following information):**
 - OS: Windows
 - Version: 10
- Python: 3.7.3
- Ludwig version: 0.1.1

**Comment by w4nderlust** [comment]
The YAML syntax requires a space after the key, so your model definition is not syntactically correct. A correct version would be:
```
ludwig experiment --data_csv C:\Users\name\Downloads\20140306_20190305_EOD\AAPL.csv --model_definition "{input_features: [{name: date, type: timeseries}], output_features: [{name: close, type: numerical}]}"
```
This should solve the issue, so I'm closing it, please keep posting if that's not the case and I will reopen the issue.
