### ISSUE TITLE
InvalidArgumentError: 'visible_device_list' listed an invalid GPU id '0' but visible device count is -1

### ISSUE THREAD

**Issue by renatochacon** [uber/ludwig#365]
Hello. I'm trying to predict using: 
ludwig predict --data_csv train.csv --model_pathresults/experiment_run_0/model/

But my terminal gives me: 

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

███████████████████████
█ █ █ █  ▜█ █ █ █ █   █
█ █ █ █ █ █ █ █ █ █ ███
█ █   █ █ █ █ █ █ █ ▌ █
█ █████ █ █ █ █ █ █ █ █
█     █  ▟█     █ █   █
███████████████████████
ludwig v0.1.2 - Predict

Dataset path: train.csv
Model path: results/experiment_run_0/model/
Output path: results_0

Found hdf5 with the same filename of the csv, using it instead
Loading metadata from: results/experiment_run_0/model/train_set_metadata.json
Loading data from: train.hdf5
/home/renatochacon/Documentos/venv1/lib/python3.5/site-packages/h5py/_hl/dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  "Use dataset[()] instead.", H5pyDeprecationWarning)

╒═══════════════╕
│ LOADING MODEL │
╘═══════════════╛

From /home/renatochacon/Documentos/venv1/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
  embedding_size (50) is greater than vocab_size (4). Setting embedding size to be equal to vocab_size.
  embedding_size (50) is greater than vocab_size (3). Setting embedding size to be equal to vocab_size.
  embedding_size (50) is greater than vocab_size (5). Setting embedding size to be equal to vocab_size.
From /home/renatochacon/Documentos/venv1/lib/python3.5/site-packages/tensorflow/python/ops/array_grad.py:425: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.

╒═════════╕
│ PREDICT │
╘═════════╛

2019-06-05 22:47:03.956082: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-06-05 22:47:03.971669: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2019-06-05 22:47:03.971716: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:148] kernel driver does not appear to be running on this host (renatochacon-Inspiron-5566): /proc/driver/nvidia/version does not exist
Traceback (most recent call last):
  File "/home/renatochacon/Documentos/venv1/bin/ludwig", line 11, in <module>
    load_entry_point('ludwig==0.1.2', 'console_scripts', 'ludwig')()
  File "/home/renatochacon/Documentos/venv1/lib/python3.5/site-packages/ludwig-0.1.2-py3.5.egg/ludwig/cli.py", line 102, in main
  File "/home/renatochacon/Documentos/venv1/lib/python3.5/site-packages/ludwig-0.1.2-py3.5.egg/ludwig/cli.py", line 63, in __init__
  File "/home/renatochacon/Documentos/venv1/lib/python3.5/site-packages/ludwig-0.1.2-py3.5.egg/ludwig/cli.py", line 78, in predict
  File "/home/renatochacon/Documentos/venv1/lib/python3.5/site-packages/ludwig-0.1.2-py3.5.egg/ludwig/predict.py", line 368, in cli
  File "/home/renatochacon/Documentos/venv1/lib/python3.5/site-packages/ludwig-0.1.2-py3.5.egg/ludwig/predict.py", line 105, in full_predict
  File "/home/renatochacon/Documentos/venv1/lib/python3.5/site-packages/ludwig-0.1.2-py3.5.egg/ludwig/predict.py", line 174, in predict
  File "/home/renatochacon/Documentos/venv1/lib/python3.5/site-packages/ludwig-0.1.2-py3.5.egg/ludwig/models/model.py", line 1219, in predict
  File "/home/renatochacon/Documentos/venv1/lib/python3.5/site-packages/ludwig-0.1.2-py3.5.egg/ludwig/models/model.py", line 221, in initialize_session
  File "/home/renatochacon/Documentos/venv1/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1551, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/home/renatochacon/Documentos/venv1/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 676, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 'visible_device_list' listed an invalid GPU id '0' but visible device count is -1

I've had many problems while trying to use Ludwig such and I've found lots of different solution for them, but I'm really stuck with that one now. 

If you find it useful, here's my pip freeze --local
absl-py==0.7.1
astor==0.8.0
atomicwrites==1.3.0
attrs==19.1.0
bleach==1.5.0
blis==0.2.4
certifi==2019.3.9
chardet==3.0.4
cloudpickle==1.1.1
cycler==0.10.0
cymem==2.0.2
Cython==0.29.10
dask==1.2.2
decorator==4.4.0
enum34==1.1.6
gast==0.2.2
google-pasta==0.1.7
grpcio==1.21.1
h5py==2.9.0
html5lib==0.9999999
idna==2.8
importlib-metadata==0.17
joblib==0.13.2
jsonschema==3.0.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
ludwig==0.1.2
Markdown==3.1.1
matplotlib==3.0.3
mock==3.0.5
more-itertools==7.0.0
murmurhash==1.0.2
networkx==2.3
numpy==1.16.4
packaging==19.0
pandas==0.24.2
pathlib2==2.3.3
Pillow==6.0.0
pkg-resources==0.0.0
plac==0.9.6
pluggy==0.12.0
preshed==2.0.1
protobuf==3.8.0
py==1.8.0
pyparsing==2.4.0
pyrsistent==0.15.2
pytest==4.6.2
python-dateutil==2.8.0
pytz==2019.1
PyWavelets==1.0.3
PyYAML==5.1
requests==2.22.0
scikit-image==0.14.2
scikit-learn==0.21.2
scipy==1.3.0
seaborn==0.9.0
six==1.12.0
spacy==2.1.4
srsly==0.0.5
tabulate==0.8.3
tb-nightly==1.14.0a20190301
tensorboard==1.13.1
tensorflow==1.13.1
tensorflow-estimator==1.13.0
tensorflow-gpu==1.13.1
tensorflow-tensorboard==0.4.0
termcolor==1.1.0
tf-estimator-nightly==1.14.0.dev2019030115
thinc==7.0.4
toolz==0.9.0
tqdm==4.32.1
urllib3==1.25.3
wasabi==0.2.2
wcwidth==0.1.7
Werkzeug==0.15.4
zipp==0.5.1

**Comment by msaisumanth** [comment]
So it looks like the CUDA device is not being recognized. Could you please try this 

```code
from tensorflow.python.client import device_lib

device_lib.list_local_devices()
```

and check if the device is being recognized?

**Comment by renatochacon** [comment]
Thank you for replying. I tried it and this is what I got in response:

python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tensorflow.python.client import device_lib
>>> device_lib.list_local_devices()
2019-06-06 15:28:04.826866: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-06-06 15:28:05.141060: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2019-06-06 15:28:05.141403: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:148] kernel driver does not appear to be running on this host (renatochacon-Inspiron-5566): /proc/driver/nvidia/version does not exist
2019-06-06 15:28:05.385150: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2904000000 Hz
2019-06-06 15:28:05.400780: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x4541e20 executing computations on platform Host. Devices:
2019-06-06 15:28:05.400891: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 5361070830031947965
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 13502562979654773177
physical_device_desc: "device: XLA_CPU device"
]
>>> from tensorflow.python.client import device_lib
>>> device_lib.list_local_devices()
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 14719442422863641000
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 2043866270598759688
physical_device_desc: "device: XLA_CPU device"
]

Unfortunately, I still don't know how to proceed in order to solve it. Any help would be greatly appreciated

**Comment by msaisumanth** [comment]
so yeah, it looks like your device is not being recognized by tensorflow. were you able to use the GPU for modeling before this? you can try a docker instance (nvidia-docker or sth) to simplify the setup

**Comment by w4nderlust** [comment]
It could also be the case that the cuda and cudnn versions you have installed are not compatible with your tensorflow version. Anyway, this doesn't seem to be a Ludwig related issue, but an issue regarding your tensorflow installation, so I'm closing this issue. You can keep posting in this thread after it is closed and we can try to help you out.
