### ISSUE TITLE
Unable to predict on unseen data: Error complaining about my output feature

### ISSUE THREAD

**Issue by zackthefair** [uber/ludwig#372]
I can't seem to predict on unseem data. 

I'm using Ludwig to train the titanic dataset train.csv, which is doing fine.

But now that I've trained my model, I want to predict over the test.csv dataset, which doesn't have the target column "Survived". But it gives me an error, basically saying KeyError: 'Survived'.

I remember that an older version of ludwig had the --only_predict parameter, which would fit perfectly in this case. But now not only it doesn't appear on the website and it's not recognizable when I try to use it. 

Just so you know, my commands were:

!ludwig train --data_csv train.csv --model_definition_file modelo.yaml (which performed well)
!ludwig predict --data_csv test.csv --model_path results/experiment_run_0/model/ (which gave me the error KeyError: 'Survived')

I'd be really glad to have some help with that.

**Comment by w4nderlust** [comment]
@zackthefair we recently split the predict command in two: predict and test. Install the most recent version of ludwig with `pip uninstall ludwig` and `pip install git+http://github.com/uber/ludwig.git` and use the predict function, it should work fine.

A little more explanation for posterity: before the predict function had a `--only_predictions` parameter that allowed to do what you are looking for, then the logic changed and the parameters was `--preform_test` but most users where still confused, so we decided to split in two functions, `predict` that doesn't require any output column and only predicts, and `test` that requires the output column and also computes measures of the quality of the prediction.

**Comment by w4nderlust** [comment]
Closing, feel free to keep commenting here if you still have problems.

**Comment by zackthefair** [comment]
Thank you for your reply, @w4nderlust 

Unfortunately, the problem persists. I'm aware of the predict and test commands. Even though I've mentioned the --only_predictions parameter, I'm using Ludwig's most recent version (or at least I think I am) on Colab, so I just use !git clone https://github.com/uber/ludwig.git > !pip install -r requirements.txt > !python setup.py install.

I'll try to be clear.

my yaml file is:

input_features:
    -
        name: Pclass
        type: category
    -
        name: Sex
        type: category
    -
        name: Age
        type: numerical
        preprocessing:
          missing_value_strategy: fill_with_mean
    -
        name: SibSp
        type: numerical
    -
        name: Parch
        type: numerical
    -
        name: Fare
        type: numerical

    -
        name: Embarked
        type: category


output_features:
    -
        name: Survived
        type: binary

Firstly, I train train.csv file, which contain target column "Survived". Then, considering the model I trained, I want to predict for survivors over the test.csv file, which doen NOT contain "Survived" column. Like mentioned before, the error appears after I use the predict command. After I type

!ludwig train --data_csv train.csv --model_definition_file modelo.yaml

and then

!ludwig predict --data_csv test.csv --model_path results/experiment_run_0/model/

Terminal gives me: 
WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

███████████████████████
█ █ █ █  ▜█ █ █ █ █   █
█ █ █ █ █ █ █ █ █ █ ███
█ █   █ █ █ █ █ █ █ ▌ █
█ █████ █ █ █ █ █ █ █ █
█     █  ▟█     █ █   █
███████████████████████
ludwig v0.1.2 - Predict

Dataset path: test.csv
Model path: results/experiment_run_0/model/
Output path: results_0

Loading metadata from: results/experiment_run_0/model/train_set_metadata.json
/usr/local/lib/python3.6/dist-packages/ludwig-0.1.2-py3.6.egg/ludwig/features/numerical_feature.py:66: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 2657, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Survived'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ludwig", line 11, in <module>
    load_entry_point('ludwig==0.1.2', 'console_scripts', 'ludwig')()
  File "/usr/local/lib/python3.6/dist-packages/ludwig-0.1.2-py3.6.egg/ludwig/cli.py", line 102, in main
  File "/usr/local/lib/python3.6/dist-packages/ludwig-0.1.2-py3.6.egg/ludwig/cli.py", line 63, in __init__
  File "/usr/local/lib/python3.6/dist-packages/ludwig-0.1.2-py3.6.egg/ludwig/cli.py", line 78, in predict
  File "/usr/local/lib/python3.6/dist-packages/ludwig-0.1.2-py3.6.egg/ludwig/predict.py", line 368, in cli
  File "/usr/local/lib/python3.6/dist-packages/ludwig-0.1.2-py3.6.egg/ludwig/predict.py", line 87, in full_predict
  File "/usr/local/lib/python3.6/dist-packages/ludwig-0.1.2-py3.6.egg/ludwig/data/preprocessing.py", line 737, in preprocess_for_prediction
  File "/usr/local/lib/python3.6/dist-packages/ludwig-0.1.2-py3.6.egg/ludwig/data/preprocessing.py", line 65, in build_dataset
  File "/usr/local/lib/python3.6/dist-packages/ludwig-0.1.2-py3.6.egg/ludwig/data/preprocessing.py", line 93, in build_dataset_df
  File "/usr/local/lib/python3.6/dist-packages/ludwig-0.1.2-py3.6.egg/ludwig/data/preprocessing.py", line 156, in build_data
  File "/usr/local/lib/python3.6/dist-packages/ludwig-0.1.2-py3.6.egg/ludwig/data/preprocessing.py", line 177, in handle_missing_values
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Survived'

**Comment by w4nderlust** [comment]
@zackthefair thanks, the issue should be solved after the latest commit. Can you please confirm it?
