### ISSUE TITLE
ValueError: could not broadcast input array from shape (259,194,3) into shape (225,225,3)

### ISSUE THREAD

**Issue by alexiross** [uber/ludwig#394]
Unable to create an image classification experiment, I received the following error:

> ValueError: could not broadcast input array from shape (259,194,3) into shape (225,225,3)

I just used standard jpg images.

**Comment by msaisumanth** [comment]
@alexiross please add your model definition and the full stacktrace. Also, are all your images of the same size?

**Comment by alexiross** [comment]
Sure no problem, the images themselves are roughly the same size; they are quite small however around 200 x 300 pixels (perhaps the issue).

```
input_features:
    -
        name: image_path
        type: image
        encoder: stacked_cnn

output_features:
    -
        name: class
        type: category

```

**Comment by alexiross** [comment]
```
ludwig experiment \
  --data_csv dog_cat.csv \
  --model_definition_file model_definition.yaml
```

**Comment by alexiross** [comment]
```
File "/home/alexi/anaconda3/envs/my_env/lib/python3.7/site-packages/ludwig/features/image_feature.py", line 215, in add_feature_data
    data[feature['name']][i, :, :, :] = img
ValueError: could not broadcast input array from shape (1311,1920,3) into shape (1610,1920,3)
```

**Comment by alexiross** [comment]
I tried with larger images and I get the same error. (see above)

**Comment by alexiross** [comment]
```
ludwig v0.1.2 - Experiment

Experiment name: experiment
Model name: run
Output path: results/experiment_run_1


ludwig_version: '0.1.2'
command: ('/home/alexi/anaconda3/envs/my_env/bin/ludwig experiment --data_csv '
 'dog_cat.csv --model_definition_file model_definition.yaml')
random_seed: 42
input_data: 'dog_cat.csv'
model_definition: {   'combiner': {'type': 'concat'},
    'input_features': [   {   'encoder': 'stacked_cnn',
                              'name': 'image_path',
                              'preprocessing': {},
                              'tied_weights': None,
                              'type': 'image'}],
    'output_features': [   {   'dependencies': [],
                               'loss': {   'class_similarities_temperature': 0,
                                           'class_weights': 1,
                                           'confidence_penalty': 0,
                                           'distortion': 1,
                                           'labels_smoothing': 0,
                                           'negative_samples': 0,
                                           'robust_lambda': 0,
                                           'sampler': None,
                                           'type': 'softmax_cross_entropy',
                                           'unique': False,
                                           'weight': 1},
                               'name': 'class',
                               'reduce_dependencies': 'sum',
                               'reduce_input': 'sum',
                               'top_k': 3,
                               'type': 'category'}],
    'preprocessing': {   'bag': {   'fill_value': '',
                                    'format': 'space',
                                    'lowercase': False,
                                    'missing_value_strategy': 'fill_with_const',
                                    'most_common': 10000},
                         'binary': {   'fill_value': 0,
                                       'missing_value_strategy': 'fill_with_const'},
                         'category': {   'fill_value': '<UNK>',
                                         'lowercase': False,
                                         'missing_value_strategy': 'fill_with_const',
                                         'most_common': 10000},
                         'force_split': False,
                         'image': {   'in_memory': True,
                                      'missing_value_strategy': 'backfill',
                                      'resize_method': 'crop_or_pad'},
                         'numerical': {   'fill_value': 0,
                                          'missing_value_strategy': 'fill_with_const'},
                         'sequence': {   'fill_value': '',
                                         'format': 'space',
                                         'lowercase': False,
                                         'missing_value_strategy': 'fill_with_const',
                                         'most_common': 20000,
                                         'padding': 'right',
                                         'padding_symbol': '<PAD>',
                                         'sequence_length_limit': 256,
                                         'unknown_symbol': '<UNK>'},
                         'set': {   'fill_value': '',
                                    'format': 'space',
                                    'lowercase': False,
                                    'missing_value_strategy': 'fill_with_const',
                                    'most_common': 10000},
                         'split_probabilities': (0.7, 0.1, 0.2),
                         'stratify': None,
                         'text': {   'char_format': 'characters',
                                     'char_most_common': 70,
                                     'char_sequence_length_limit': 1024,
                                     'fill_value': '',
                                     'lowercase': True,
                                     'missing_value_strategy': 'fill_with_const',
                                     'padding': 'right',
                                     'padding_symbol': '<PAD>',
                                     'unknown_symbol': '<UNK>',
                                     'word_format': 'space_punct',
                                     'word_most_common': 20000,
                                     'word_sequence_length_limit': 256},
                         'timeseries': {   'fill_value': '',
                                           'format': 'space',
                                           'missing_value_strategy': 'fill_with_const',
                                           'padding': 'right',
                                           'padding_value': 0,
                                           'timeseries_length_limit': 256}},
    'training': {   'batch_size': 128,
                    'bucketing_field': None,
                    'decay': False,
                    'decay_rate': 0.96,
                    'decay_steps': 10000,
                    'dropout_rate': 0.0,
                    'early_stop': 5,
                    'epochs': 100,
                    'eval_batch_size': 0,
                    'gradient_clipping': None,
                    'increase_batch_size_on_plateau': 0,
                    'increase_batch_size_on_plateau_max': 512,
                    'increase_batch_size_on_plateau_patience': 5,
                    'increase_batch_size_on_plateau_rate': 2,
                    'learning_rate': 0.001,
                    'learning_rate_warmup_epochs': 5,
                    'optimizer': {   'beta1': 0.9,
                                     'beta2': 0.999,
                                     'epsilon': 1e-08,
                                     'type': 'adam'},
                    'reduce_learning_rate_on_plateau': 0,
                    'reduce_learning_rate_on_plateau_patience': 5,
                    'reduce_learning_rate_on_plateau_rate': 0.5,
                    'regularization_lambda': 0,
                    'regularizer': 'l2',
                    'staircase': False,
                    'validation_field': 'combined',
                    'validation_measure': 'loss'}}


Using full raw csv, no hdf5 and json file with the same name have been found
Building dataset (it may take a while)
Traceback (most recent call last):
  File "/home/alexi/anaconda3/envs/my_env/bin/ludwig", line 10, in <module>
    sys.exit(main())
  File "/home/alexi/anaconda3/envs/my_env/lib/python3.7/site-packages/ludwig/cli.py", line 94, in main
    CLI()
  File "/home/alexi/anaconda3/envs/my_env/lib/python3.7/site-packages/ludwig/cli.py", line 60, in __init__
    getattr(self, args.command)()
  File "/home/alexi/anaconda3/envs/my_env/lib/python3.7/site-packages/ludwig/cli.py", line 65, in experiment
    experiment.cli(sys.argv[2:])
  File "/home/alexi/anaconda3/envs/my_env/lib/python3.7/site-packages/ludwig/experiment.py", line 472, in cli
    experiment(**vars(args))
  File "/home/alexi/anaconda3/envs/my_env/lib/python3.7/site-packages/ludwig/experiment.py", line 200, in experiment
    **kwargs
  File "/home/alexi/anaconda3/envs/my_env/lib/python3.7/site-packages/ludwig/train.py", line 252, in full_train
    random_seed=random_seed
  File "/home/alexi/anaconda3/envs/my_env/lib/python3.7/site-packages/ludwig/data/preprocessing.py", line 403, in preprocess_for_training
    random_seed
  File "/home/alexi/anaconda3/envs/my_env/lib/python3.7/site-packages/ludwig/data/preprocessing.py", line 525, in _preprocess_csv_for_training
    random_seed=random_seed
  File "/home/alexi/anaconda3/envs/my_env/lib/python3.7/site-packages/ludwig/data/preprocessing.py", line 62, in build_dataset
    **kwargs
  File "/home/alexi/anaconda3/envs/my_env/lib/python3.7/site-packages/ludwig/data/preprocessing.py", line 90, in build_dataset_df
    global_preprocessing_parameters
  File "/home/alexi/anaconda3/envs/my_env/lib/python3.7/site-packages/ludwig/data/preprocessing.py", line 165, in build_data
    preprocessing_parameters
  File "/home/alexi/anaconda3/envs/my_env/lib/python3.7/site-packages/ludwig/features/image_feature.py", line 215, in add_feature_data
    data[feature['name']][i, :, :, :] = img

```

**Comment by alexiross** [comment]
`ValueError: could not broadcast input array from shape (1311,1920,3) into shape (1610,1920,3)
`

**Comment by msaisumanth** [comment]
@alexiross so the issue is that all your images in the data are not of the same size. We have a logic to handle that case, but something else is failing. Can you please try this: 

```yaml
input_features:
    -
        name: image_path
        type: image
        encoder: stacked_cnn
        resize_image: true
        preprocessing:
          width: 224
          height: 224
```

I used 224 because (224, 224, 3) is a common size used for ImageNet models so you'll be able to use pretrained models. Let me know if you still have issues after this

**Comment by alexiross** [comment]
Work perfectly thank you!

**Comment by w4nderlust** [comment]
@msaisumanth we should probably sorround that with a try and except and print in the except domething like "Ludwig expects all your images to have the same size, if they don't have the same size please specify the width and height to use in the preprocessing. Refer to the user guide (image features preprocessing) for more details".
