### ISSUE TITLE
Training on images failure

### ISSUE THREAD

**Issue by FellCrustacean8** [uber/ludwig#426]
When executing my training python script, the following is returned.
```
Traceback (most recent call last):
  File "train.py", line 14, in <module>
    train_stats = model.train(data_csv="./dataset.csv")
  File "/home/user/.local/lib/python3.7/site-packages/ludwig/api.py", line 441, in train
    debug=debug,
  File "/home/user/.local/lib/python3.7/site-packages/ludwig/train.py", line 252, in full_train
    random_seed=random_seed
  File "/home/user/.local/lib/python3.7/site-packages/ludwig/data/preprocessing.py", line 403, in preprocess_for_training
    random_seed
  File "/home/user/.local/lib/python3.7/site-packages/ludwig/data/preprocessing.py", line 525, in _preprocess_csv_for_training
    random_seed=random_seed
  File "/home/user/.local/lib/python3.7/site-packages/ludwig/data/preprocessing.py", line 62, in build_dataset
    **kwargs
  File "/home/user/.local/lib/python3.7/site-packages/ludwig/data/preprocessing.py", line 83, in build_dataset_df
    global_preprocessing_parameters
  File "/home/user/.local/lib/python3.7/site-packages/ludwig/data/preprocessing.py", line 116, in build_metadata
    feature['preprocessing']
  File "/home/user/.local/lib/python3.7/site-packages/ludwig/utils/misc.py", line 97, in merge_dict
    for k, v in merge_dct.items():
AttributeError: 'list' object has no attribute 'items'
```
```
from ludwig.api import LudwigModel

model_definition = {
    "input_features":[
        {"name":"image_path", "type":"image", "preprocessing":[{"height": "128", "width": "128"}],"resize_method": "interpolate"}
    ],
    "output_features":[
        {"name":"plate","type":"text"}
    ]
}

model = LudwigModel(model_definition)

train_stats = model.train(data_csv="./dataset.csv")
```

CSV is formatted like this.

`image_path, plate
./crop_m1/I00000.png, 9B52145
./crop_h1/I00000.png, 9B52145
./crop_m1/I00001.png, 6B94558
./crop_h1/I00001.png, 6B94558
./crop_m1/I00002.png, 8B90164
./crop_h1/I00002.png, 8B90164
./crop_m1/I00003.png, 5B11181
./crop_h1/I00003.png, 5B11181
./crop_m1/I00004.png, 8B79697
./crop_h1/I00004.png, 8B79697
./crop_m1/I00005.png, 8B90164`

**Comment by w4nderlust** [comment]
Preprocessing is not a list but a dictionary and resize method is also a preprocessing parameter.
```
model_definition = {
    "input_features":[
        {"name":"image_path", "type":"image", "preprocessing":{"height": "128", "width": "128", "resize_method": "interpolate"}}
    ],
    "output_features":[
        {"name":"plate","type":"text"}
    ]
}
```

**Comment by FellCrustacean8** [comment]
Thank you, it resolved that issue. But now I'm encountering this.
`
Traceback (most recent call last):
  File "train.py", line 14, in <module>
    train_stats = model.train(data_csv="./dataset.csv")
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/api.py", line 441, in train
    debug=debug,
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/train.py", line 252, in full_train
    random_seed=random_seed
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/data/preprocessing.py", line 403, in preprocess_for_training
    random_seed
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/data/preprocessing.py", line 525, in _preprocess_csv_for_training
    random_seed=random_seed
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/data/preprocessing.py", line 62, in build_dataset
    **kwargs
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/data/preprocessing.py", line 83, in build_dataset_df
    global_preprocessing_parameters
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/data/preprocessing.py", line 123, in build_metadata
    dataset_df[feature['name']].astype(str),
  File "/home/mark/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/mark/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'plate'`

**Comment by w4nderlust** [comment]
make sure you have a column named `plate` in your dataset. Given the excert you pasted, the second columns name is ` plate` with a space before the name.
