### ISSUE TITLE
ValueError: Cannot convert an unknown Dimension to a Tensor

### ISSUE THREAD

**Issue by FellCrustacean8** [uber/ludwig#434]
When training the model, I get the following output.

```
/home/mark/.local/lib/python3.7/site-packages/h5py/_hl/dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  "Use dataset[()] instead.", H5pyDeprecationWarning)
Traceback (most recent call last):
  File "train.py", line 14, in <module>
    train_stats = model.train(data_csv="./dataset.csv")
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/api.py", line 441, in train
    debug=debug,
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/train.py", line 301, in full_train
    debug=debug
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/train.py", line 442, in train
    debug=debug
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/models/model.py", line 108, in __init__
    **kwargs
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/models/model.py", line 182, in __build
    is_training=self.is_training
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/models/outputs.py", line 43, in build_outputs
    **kwargs
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/models/outputs.py", line 93, in build_single_output
    **kwargs
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/features/base_feature.py", line 314, in concat_dependencies_and_build_output
    **kwargs
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/features/text_feature.py", line 266, in build_output
    kwarg=kwargs
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/features/sequence_feature.py", line 320, in build_sequence_output
    eval_loss
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/features/sequence_feature.py", line 445, in sequence_measures
    self.name
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/models/modules/measure_modules.py", line 73, in masked_accuracy
    maxlen=correct_predictions.shape[1], dtype=tf.int32)
  File "/home/mark/.local/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 3088, in sequence_mask
    maxlen = ops.convert_to_tensor(maxlen)
  File "/home/mark/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1087, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "/home/mark/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1145, in convert_to_tensor_v2
    as_ref=False)
  File "/home/mark/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1224, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/mark/.local/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 358, in _dimension_tensor_conversion_function
    raise ValueError("Cannot convert an unknown Dimension to a Tensor: %s" % d)
ValueError: Cannot convert an unknown Dimension to a Tensor: ?
```
Python Training Script

```
from ludwig.api import LudwigModel

model_definition = {
    "input_features":[
        {"name":"image_path", "type":"image", "preprocessing":{"height": "128", "width": "128", "resize_method": "interpolate"}}
    ],
    "output_features":[
        {"name":"plate","type":"text"}
    ]
}

model = LudwigModel(model_definition)
train_stats = model.train(data_csv="./dataset.csv")
```
CSV Format

```
image_path,plate
./crop_m1/I00000.png,9B52145
./crop_h1/I00000.png,9B52145
./crop_m1/I00001.png,6B94558
./crop_h1/I00001.png,6B94558
./crop_m1/I00002.png,8B90164
./crop_h1/I00002.png,8B90164
```

I'm using version 0.1.2, the newest release in pip. I also receive the same error when building from master branch.

Looking at previous issues with the same error. And following the corrective action did not resolve this case.

**Comment by w4nderlust** [comment]
Please use the code in master and let me know if the problem is still there. Plus, your output should be tokenized at the character level, check the documentation for that.

**Comment by FellCrustacean8** [comment]
I'm a little confused of how to use it after reading the documentation. I currently have it written the output features like this.
```
"output_features":[
        {"name":"plate","type":"text", "char_tokenizer":"characters"}
]
```
And if I am utilizing it properly, I'm still getting the same error.

**Comment by w4nderlust** [comment]
That's incorrect. It should be:
```
"output_features":[ 
        {"name":"plate","type":"text", "level": "char"}
]
```
Text features at the moment save both word and char tokens, with level you are specifying that you want to generate char by char.
But that's probably not your issue. One possibility could be that you have the hdf5 and json cache files from previous attempt to train a model, make sure you delete them.
If neither of those things work and you are using the code from master, then please provide a fully reproducible, because I tried to reproduce it myself and everything works fine.

**Comment by FellCrustacean8** [comment]
Thank you, that resolved the issue.

**Comment by w4nderlust** [comment]
Great!
