### ISSUE TITLE
models trained with ludwig-0.1.2 won't load in ludwig-0.2

### ISSUE THREAD

**Issue by carlogrisetti** [uber/ludwig#453]
[Here](https://github.com/uber/ludwig/files/3429228/model_definition.txt) is the model definition i'm using

Basically a model trained with 0.1.2 (and tensorflow-gpu 1.13.1) will output this error when trying to load it using ludwig 0.2 (and tensorflow-gpu 1.14). Don't know if it's ludwig-side, tensorflow-side, or it's just as it is and I need to accept this and go on retrain the models, due to the way models are "saved" (I remember past discussions on the method ludwig uses to save the trained model).

The error is:
`Not found: Key optimizer/intent/fc_0/biases/Adam not found in checkpoint [[{{node save/RestoreV2}}]]`
amongst other instances of the same "Adam" optimizer looked for but not found.

A [sample dataset](https://github.com/uber/ludwig/files/3429245/sample_dataset.csv.txt) is also attached. Of course it does not give any meaningful results, but any saved model no matter how bad it is should do the trick.

**Comment by w4nderlust** [comment]
It's most likely a tensorflow 1.14 thing as there hasn't been much change in saved models. Try to uninstall 1.13 and install 1.13.1 as I'm not using anything specific from 1.14, and see if it works.
Anyway, a generic rule, while Ludwig is in v0.x every second digit release could change compatibility. It is part of the reason why we started with v0.1 and not v1.0, the api and other things are not stabilitzed yet, even if in this casethe reason why it does not work is likely tf.

**Comment by carlogrisetti** [comment]
Will try to downgrade TF.
I was pointing that out since it's the first time that this retrocompatibility sort of breaks.

**Comment by carlogrisetti** [comment]
Unfortunately it seems that it's not TF breaking retrocompatibility
On a system that had TF 1.13.1 installed I upgraded ludwig and manually changed the requirements.txt to match 1.13.1 (instead of 1.14.0).
The same issue presented itself with the same exact behavior. I am reproducing it with the latest master.

Might be that you updated the various model templates used within ludwig and it's trying to restore a checkpoint with a different template than the one that was used to generate it?
It seems as it could just be a different naming convention on that optimizer, but I'm not skilled enough to trace it back to the real reason.

I don't think it will be easily fixable, or simply I think you won't be willing to fix that, since it would break compatibility with 0.2+, unless you can find a workaround to be able to support\load both "versions", but I'm open to surprises :)

`stack below`
2019-08-13 14:36:49.652032: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key optimizer/intent/fc_0/biases/Adam not found in checkpoint
Traceback (most recent call last):
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key optimizer/intent/fc_0/biases/Adam not found in checkpoint
	 [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 1276, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key optimizer/intent/fc_0/biases/Adam not found in checkpoint
	 [[node save/RestoreV2 (defined at C:\somepath\Python\Python36\lib\site-packages\ludwig\models\model.py:216) ]]

Caused by op 'save/RestoreV2', defined at:
  File "C:\someotherpath\myprogram_api.py", line 418, in <module>
    mpe = MyProgramEngine()
  File "C:\someotherpath\myprogram_engine.py", line 22, in __init__
    self.model_load()
  File "C:\someotherpath\myprogram_engine.py", line 33, in model_load
    self.model = LudwigModel.load("model\\model")
  File "C:\somepath\Python\Python36\lib\site-packages\ludwig\api.py", line 217, in load
    model, model_definition = load_model_and_definition(model_dir)
  File "C:\somepath\Python\Python36\lib\site-packages\ludwig\models\model.py", line 1676, in load_model_and_definition
    model = Model.load(model_dir, use_horovod=use_horovod)
  File "C:\somepath\Python\Python36\lib\site-packages\ludwig\models\model.py", line 1379, in load
    model = Model(use_horovod=use_horovod, **hyperparameters)
  File "C:\somepath\Python\Python36\lib\site-packages\ludwig\models\model.py", line 113, in __init__
    **kwargs
  File "C:\somepath\Python\Python36\lib\site-packages\ludwig\models\model.py", line 216, in __build
    self.saver = tf.train.Saver()
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 832, in __init__
    self.build()
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 332, in _AddRestoreOps
    restore_sequentially)
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 580, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1655, in restore_v2
    name=name)
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Key optimizer/intent/fc_0/biases/Adam not found in checkpoint
	 [[node save/RestoreV2 (defined at C:\somepath\Python\Python36\lib\site-packages\ludwig\models\model.py:216) ]]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 1286, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 1591, in object_graph_key_mapping
    checkpointable.OBJECT_GRAPH_PROTO_KEY)
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 370, in get_tensor
    status)
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\someotherpath\myprogram_api.py", line 418, in <module>
    mpe = MyProgramEngine()
  File "C:\someotherpath\myprogram_engine.py", line 22, in __init__
    self.model_load()
  File "C:\someotherpath\myprogram_engine.py", line 40, in model_load
    self.model_predict()
  File "C:\someotherpath\myprogram_engine.py", line 49, in model_predict
    self.prediction = self.model.predict(data_df=pd.DataFrame({'utterance': [self.utterance]}))
  File "C:\somepath\Python\Python36\lib\site-packages\ludwig\api.py", line 867, in predict
    evaluate_performance=False,
  File "C:\somepath\Python\Python36\lib\site-packages\ludwig\api.py", line 758, in _predict
    session=getattr(self.model, 'session', None)
  File "C:\somepath\Python\Python36\lib\site-packages\ludwig\models\model.py", line 1235, in predict
    self.restore(session, self.weights_save_path)
  File "C:\somepath\Python\Python36\lib\site-packages\ludwig\models\model.py", line 1370, in restore
    self.saver.restore(session, weights_path)
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 1292, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key optimizer/intent/fc_0/biases/Adam not found in checkpoint
	 [[node save/RestoreV2 (defined at C:\somepath\Python\Python36\lib\site-packages\ludwig\models\model.py:216) ]]

Caused by op 'save/RestoreV2', defined at:
  File "C:\someotherpath\myprogram_api.py", line 418, in <module>
    mpe = MyProgramEngine()
  File "C:\someotherpath\myprogram_engine.py", line 22, in __init__
    self.model_load()
  File "C:\someotherpath\myprogram_engine.py", line 33, in model_load
    self.model = LudwigModel.load("model\\model")
  File "C:\somepath\Python\Python36\lib\site-packages\ludwig\api.py", line 217, in load
    model, model_definition = load_model_and_definition(model_dir)
  File "C:\somepath\Python\Python36\lib\site-packages\ludwig\models\model.py", line 1676, in load_model_and_definition
    model = Model.load(model_dir, use_horovod=use_horovod)
  File "C:\somepath\Python\Python36\lib\site-packages\ludwig\models\model.py", line 1379, in load
    model = Model(use_horovod=use_horovod, **hyperparameters)
  File "C:\somepath\Python\Python36\lib\site-packages\ludwig\models\model.py", line 113, in __init__
    **kwargs
  File "C:\somepath\Python\Python36\lib\site-packages\ludwig\models\model.py", line 216, in __build
    self.saver = tf.train.Saver()
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 832, in __init__
    self.build()
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 332, in _AddRestoreOps
    restore_sequentially)
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 580, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1655, in restore_v2
    name=name)
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\somepath\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key optimizer/intent/fc_0/biases/Adam not found in checkpoint
	 [[node save/RestoreV2 (defined at C:\somepath\Python\Python36\lib\site-packages\ludwig\models\model.py:216) ]]

**Comment by carlogrisetti** [comment]
I just found out that this issue only appears on some models.
Models with image inputs (both resnet 8 and resnet 34), category inputs, category outputs and numerical outputs work fine even after ludwig-0.2.0 and tensorflow-1.14.0 upgrade.

The model that is not being able to be resored is a model that is defined like this:

input_features:
    -
        name: utterance
        type: sequence
        encoder: rnn
        cell_type: lstm
        bidirectional: true
        num_layers: 2
        reduce_output: None
        dropout: true

output_features:
    -
        name: intent
        type: category
        reduce_input: sum
        num_fc_layers: 1
        fc_size: 64
    -
        name: slots
        type: sequence
        decoder: tagger

I suspect the issue might be related to the optimizer used by the input sequence rnn encoder or the optimizer used by the output sequence tagger

**Comment by w4nderlust** [comment]
Yes that's likely, it looks like they are replacing some TF functions with Keras counterparts, and LSTMs are one of those judging by thewarnings.

**Comment by carlogrisetti** [comment]
Just to be clear, I don't think it's a "they" but "you". I was initially able to reproduce the issue with TF 1.13.1 and Ludwig-0.2.0\master so it shouldn't be a TF-related issue, but something that changed in how ludwig manages models (and my hunch was on how it built the models which have a sequence encoder \ tagger in the definition)

On my side, since it seems to be only impacting "minor" models (ie: the ones I can retrain in just a few hours), it's a "wontfix" also. It would have been much worse if the issue presented itself on image\resnet models, as those require days of training, and luckily I don't have models which contains both of them.
I just wanted to bring this to your attention, because it seems like an unwanted change that passed by unnoticed, and mostly does not do harm... but only mostly :)

**Comment by carlogrisetti** [comment]
@w4nderlust FYI, the same thing happens between ludwig 0.2 and ludwig 0.3, although this seems more obvious due to the huge framework change underneath. Might be worthy of mention in a v0.3 changelog. Errors are more or less in the same ballpark on missing\different parameters for the optimizers

**Comment by w4nderlust** [comment]
Yes this is expected, there are a bunch of different parameters for encoders and decoders too and other changes to the interface, will make sure to document those both in the Changelog and in the User Guide.

**Comment by carlogrisetti** [comment]
FYI, models trained before 0.3.0-rc1 need to be retrained. There is a breaking change somewhere that causes prediction results to be highly incorrect as compared as pre-0.3.0-rc1.
Once retrained all works fine, so it's just a FYI if some issues get opened for this.
"normal" users won't notice this and should only stick to "0.2.0 not compatible with 0.3.0" as per this original issue
