### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'websockets==7.*' distribution was not found and is required by uvicorn

### ISSUE THREAD

**Issue by aamustapha** [uber/ludwig#454]
**Describe the bug**
After a plain installation on mac, I get the following error log
```
Traceback (most recent call last):
  File "/Users/amustapha/ludwig/lib/python3.7/site-packages/setuptools-39.1.0-py3.7.egg/pkg_resources/__init__.py", line 574, in _build_master
  File "/Users/amustapha/ludwig/lib/python3.7/site-packages/setuptools-39.1.0-py3.7.egg/pkg_resources/__init__.py", line 892, in require
  File "/Users/amustapha/ludwig/lib/python3.7/site-packages/setuptools-39.1.0-py3.7.egg/pkg_resources/__init__.py", line 783, in resolve
pkg_resources.ContextualVersionConflict: (websockets 8.0.1 (/Users/amustapha/ludwig/lib/python3.7/site-packages/websockets-8.0.1-py3.7-macosx-10.14-x86_64.egg), Requirement.parse('websockets==7.*'), {'uvicorn'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/amustapha/ludwig/bin/ludwig", line 6, in <module>
    from pkg_resources import load_entry_point
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/amustapha/ludwig/lib/python3.7/site-packages/setuptools-39.1.0-py3.7.egg/pkg_resources/__init__.py", line 3086, in <module>
  File "/Users/amustapha/ludwig/lib/python3.7/site-packages/setuptools-39.1.0-py3.7.egg/pkg_resources/__init__.py", line 3070, in _call_aside
  File "/Users/amustapha/ludwig/lib/python3.7/site-packages/setuptools-39.1.0-py3.7.egg/pkg_resources/__init__.py", line 3099, in _initialize_master_working_set
  File "/Users/amustapha/ludwig/lib/python3.7/site-packages/setuptools-39.1.0-py3.7.egg/pkg_resources/__init__.py", line 576, in _build_master
  File "/Users/amustapha/ludwig/lib/python3.7/site-packages/setuptools-39.1.0-py3.7.egg/pkg_resources/__init__.py", line 589, in _build_from_requirements
  File "/Users/amustapha/ludwig/lib/python3.7/site-packages/setuptools-39.1.0-py3.7.egg/pkg_resources/__init__.py", line 778, in resolve
pkg_resources.DistributionNotFound: The 'websockets==7.*' distribution was not found and is required by uvicorn
```

**To Reproduce**

1. Fresh install on MacBook Pro
2. run `ludwig -m ludwig.train --data_train_csv R_75.csv --mdf model_definition.yaml`

Yaml file:
```
input_features:
    -
        name: epoch
        type: numerical
    -
        name: MACD
        type: numerical
    -
        name: MA13
        type: numerical
    -
        name: MA48
        type: numerical
    -
        name: upper_bb
        type: numerical
    -
        name: middle_bb
        type: numerical
    -
        name: lower_bb
        type: numerical
    -
        name: adx
        type: numerical


output_features:
    -
        name: max_profit
        type: numerical
    -
        name: change
        type: numerical
    -
        name: open
        type: numerical
    -
        name: high
        type: numerical
    -
        name: low
        type: numerical
    -
        name: close
        type: numerical
```

Data Sample
```close,epoch,high,low,open,MACD,MA13,MA48,upper_bb,middle_bb,lower_bb,adx,max_profit,change
221665.808,1563718560,221694.8075,221346.889,221544.4531,,,,221666.28912379823,221346.889,221194.34597620173,,347.91849999999977,0.15705903202724839
221541.2492,1563718620,221679.6004,221513.7461,221613.3777,,,,221666.28912379823,221430.31754999998,221194.34597620173,,165.85430000000633,0.07484512180058477
221507.2274,1563718680,221614.2174,221366.2548,221544.8507,,,,221591.48272290383,221408.96329999997,221226.4438770961,,247.96259999999893,0.11195193267483222
221383.7589,1563718740,221671.9345,221362.6583,221486.2273,,,,221553.44167563826,221397.38705,221241.33242436172,,309.27619999999297,0.13961717889582956
221165.8399,1563718800,221577.6526,221079.5956,221394.3952,,,,221648.56342474447,221333.82876,221019.09409525554,,498.0570000000007,0.2250305409095979
221128.9268,1563718860,221303.3067,221052.455,221122.9666,,,,221650.28850010873,221286.93313333334,220923.57776655795,,250.85169999999925,0.11341626885833295
220993.0361,1563718920,221125.3651,220891.6857,221070.1616,,,,221676.88995580107,221230.46921428572,220784.04847277037,,233.67939999999362,0.10573320625394916
221029.796,1563718980,221170.4593,220973.5982,220973.5982,,,,221649.81645523163,221198.3603375,220746.90421976836,,196.86109999998007,0.089048397987337
221145.9914,1563719040,221212.5409,221025.146,221052.0686,-26.55076113800169,,,221616.91654588038,221179.1143,220741.3120541196,,187.39489999998477,0.08474849862461362
220991.8338,1563719100,221237.534,220991.8338,221162.0486,-23.60463708624593,,,221589.8087045741,221160.38624999998,220730.96379542587,,245.70020000002114,0.11111889797022255
```

**Expected behavior**
I expected to see it run

~**Screenshots**
If applicable, add screenshots to help explain your problem.~

**Environment (please complete the following information):**
 - OS: Mac
 - Version 10.14.6
- Python version 3.7.2
- Ludwig version 0.2

**Additional context**

**Comment by w4nderlust** [comment]
This is peculiar, I run the same version of osx and python and I haven't encountered the error.
Will try to look into it even if reproducing may be complicated.
In the mean time you can try to update setuptools and pip. Also `uvicorn` is used only by the `serve` command, so you can get away uninstalling it if you don't plan to use the `serve` command.

**Comment by aamustapha** [comment]
Uninstalling uvicorn threw error that
```
pkg_resources.DistributionNotFound: The 'uvicorn' was not found and is required by ludwig
```
However updating `setuptools==41.0.0` did the magic.
Thank you.
