### ISSUE TITLE
TypeError with confusion matrix

### ISSUE THREAD

**Issue by hieu325** [uber/ludwig#477]
**Describe the bug**
Training data is [twitter airline sentiment](https://www.kaggle.com/crowdflower/twitter-airline-sentiment).
My model definition yaml is 
```
input_features:
    -
        name: text
        type: text
output_features:
    -
        name: airline_sentiment
        type: category
```
After training, I used ludwig test to produce test_statistics.json. When I want to visualize a confusion matrix of the output `ludwig visualize --visualization confusion_matrix -tes ./results_0/test_statistics.json` , I got TypeError

```
Traceback (most recent call last):
  File "C:\Users\huuhi\Anaconda3\Scripts\ludwig-script.py", line 11, in <module>
    load_entry_point('ludwig==0.2.1', 'console_scripts', 'ludwig')()
  File "C:\Users\huuhi\Anaconda3\lib\site-packages\ludwig-0.2.1-py3.6.egg\ludwig\cli.py", line 108, in main
  File "C:\Users\huuhi\Anaconda3\lib\site-packages\ludwig-0.2.1-py3.6.egg\ludwig\cli.py", line 64, in __init__
  File "C:\Users\huuhi\Anaconda3\lib\site-packages\ludwig-0.2.1-py3.6.egg\ludwig\cli.py", line 94, in visualize
  File "C:\Users\huuhi\Anaconda3\lib\site-packages\ludwig-0.2.1-py3.6.egg\ludwig\visualize.py", line 3119, in cli
  File "C:\Users\huuhi\Anaconda3\lib\site-packages\ludwig-0.2.1-py3.6.egg\ludwig\visualize.py", line 650, in confusion_matrix_cli
  File "C:\Users\huuhi\Anaconda3\lib\site-packages\ludwig-0.2.1-py3.6.egg\ludwig\utils\data_utils.py", line 76, in load_json
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Environment:**
 - OS: Win 10
- Python 3
- Ludwig version 0.2

**Comment by msaisumanth** [comment]
@hieu325 can you please paste the contents of test_statistics.json ?

**Comment by hieu325** [comment]
Here is the content of test_statistics.json:

```
{
    "airline_sentiment": {
        "accuracy": 0.788520669627605,
        "confusion_matrix": [
            [
                0,
                0,
                0,
                0
            ],
            [
                0,
                1611,
                175,
                75
            ],
            [
                0,
                148,
                342,
                48
            ],
            [
                0,
                85,
                88,
                355
            ]
        ],
        "hits_at_k": 1.0,
        "loss": 0.6125370047790506,
        "overall_stats": {
            "avg_f1_score_macro": 0.7246087439784766,
            "avg_f1_score_micro": 0.788520669627605,
            "avg_f1_score_weighted": 0.7868162644590411,
            "avg_precision_macro": 0.724566612966417,
            "avg_precision_micro": 0.788520669627605,
            "avg_precision_weighted": 0.788520669627605,
            "avg_recall_macro": 0.7272037773643425,
            "avg_recall_micro": 0.788520669627605,
            "avg_recall_weighted": 0.788520669627605,
            "kappa_score": 0.602478272822395,
            "token_accuracy": 0.788520669627605
        },
        "per_class_stats": {
            "<UNK>": {
                "accuracy": 1.0,
                "f1_score": 0,
                "fall_out": 0.0,
                "false_discovery_rate": 1.0,
                "false_negative_rate": 1.0,
                "false_negatives": 0,
                "false_omission_rate": 0.0,
                "false_positive_rate": 0.0,
                "false_positives": 0,
                "hit_rate": 0,
                "informedness": 0.0,
                "markedness": 0.0,
                "matthews_correlation_coefficient": 0,
                "miss_rate": 1.0,
                "negative_predictive_value": 1.0,
                "positive_predictive_value": 0,
                "precision": 0,
                "recall": 0,
                "sensitivity": 0,
                "specificity": 1.0,
                "true_negative_rate": 1.0,
                "true_negatives": 2927,
                "true_positive_rate": 0,
                "true_positives": 0
            },
            "negative": {
                "accuracy": 0.8349846258968227,
                "f1_score": 0.8696356275303644,
                "fall_out": 0.2185741088180112,
                "false_discovery_rate": 0.12635574837310193,
                "false_negative_rate": 0.13433637829124123,
                "false_negatives": 250,
                "false_omission_rate": 0.23084025854108958,
                "false_positive_rate": 0.2185741088180112,
                "false_positives": 233,
                "hit_rate": 0.8656636217087588,
                "informedness": 0.6470895128907475,
                "markedness": 0.6428039930858085,
                "matthews_correlation_coefficient": 0.6449431934442933,
                "miss_rate": 0.13433637829124123,
                "negative_predictive_value": 0.7691597414589104,
                "positive_predictive_value": 0.8736442516268981,
                "precision": 0.8736442516268981,
                "recall": 0.8656636217087588,
                "sensitivity": 0.8656636217087588,
                "specificity": 0.7814258911819888,
                "true_negative_rate": 0.7814258911819888,
                "true_negatives": 833,
                "true_positive_rate": 0.8656636217087588,
                "true_positives": 1611
            },
            "neutral": {
                "accuracy": 0.8431841475913905,
                "f1_score": 0.5984251968503936,
                "fall_out": 0.11008790288823778,
                "false_discovery_rate": 0.43471074380165287,
                "false_negative_rate": 0.3643122676579925,
                "false_negatives": 196,
                "false_omission_rate": 0.08440999138673555,
                "false_positive_rate": 0.11008790288823778,
                "false_positives": 263,
                "hit_rate": 0.6356877323420075,
                "informedness": 0.5255998294537698,
                "markedness": 0.4808792648116116,
                "matthews_correlation_coefficient": 0.5027425380578384,
                "miss_rate": 0.3643122676579925,
                "negative_predictive_value": 0.9155900086132644,
                "positive_predictive_value": 0.5652892561983471,
                "precision": 0.5652892561983471,
                "recall": 0.6356877323420075,
                "sensitivity": 0.6356877323420075,
                "specificity": 0.8899120971117622,
                "true_negative_rate": 0.8899120971117622,
                "true_negatives": 2126,
                "true_positive_rate": 0.6356877323420075,
                "true_positives": 342
            },
            "positive": {
                "accuracy": 0.8988725657669969,
                "f1_score": 0.7057654075546719,
                "fall_out": 0.051271363067945,
                "false_discovery_rate": 0.2573221757322176,
                "false_negative_rate": 0.32765151515151514,
                "false_negatives": 173,
                "false_omission_rate": 0.07064107799101671,
                "false_positive_rate": 0.051271363067945,
                "false_positives": 123,
                "hit_rate": 0.6723484848484849,
                "informedness": 0.62107712178054,
                "markedness": 0.6720367462767656,
                "matthews_correlation_coefficient": 0.6460546788843283,
                "miss_rate": 0.32765151515151514,
                "negative_predictive_value": 0.9293589220089833,
                "positive_predictive_value": 0.7426778242677824,
                "precision": 0.7426778242677824,
                "recall": 0.6723484848484849,
                "sensitivity": 0.6723484848484849,
                "specificity": 0.948728636932055,
                "true_negative_rate": 0.948728636932055,
                "true_negatives": 2276,
                "true_positive_rate": 0.6723484848484849,
                "true_positives": 355
            }
        }
    },
    "combined": {
        "accuracy": 0.788520669627605,
        "loss": 0.6125370047790506
    }
}
```

**Comment by rthiruv-lab58** [comment]
I had faced similar problems while training using custom dataset as well. What worked for me was two things,
1) I gave full path directory to the files ( test_statistics.json) and 
2) Gave the ground_truth metadata (the training Json file), which in the documentation is described as necessary. 
Documentation: https://uber.github.io/ludwig/user_guide/#confusion-matrix

Changing these two worked out for me. Let me know if it works for you too.

The command I used:
ludwig visualize --visualization confusion_matrix --normalize --top_n_class 8 --test_statistics ./results_1/test_statistics.json --ground_truth_metada train1.json

**Comment by hieu325** [comment]
@rthiruv-lab58 Thanks for the solution. It works for me, in particular, your step 2 of including training_statistics.json as ground_truth metadata.

**Comment by w4nderlust** [comment]
Just to clarify for people who may end up reading this issue: the `--ground_truth_metada` parameter accepts the metadata JSON file that is created when a dataset is used the firt time with the same name of the dataset with .JSON at the end. If the preprocessed data saving is skipped, the same information is actually present in `results/experiment_run_0/model/tran_set_metadata.json` (results and experiment run may be different in your case).
