### ISSUE TITLE
Examples in user_guide

### ISSUE THREAD

**Issue by sriki18** [uber/ludwig#481]
**Is your feature request related to a problem? Please describe.**
I am playing around with the Iris dataset to learn how to use Ludwig. I want to use the confusion matrix visualization (as an example). It was not too clear from the user guide which arguments were necessary and which arguments were optional. I initially kept getting the following error:

```
Traceback (most recent call last):
  File "C:\Users\sriki\Miniconda3\Scripts\ludwig-script.py", line 11, in <module>
    load_entry_point('ludwig==0.2.1', 'console_scripts', 'ludwig')()
  File "C:\Users\sriki\Miniconda3\lib\site-packages\ludwig-0.2.1-py3.7.egg\ludwig\cli.py", line 108, in main
  File "C:\Users\sriki\Miniconda3\lib\site-packages\ludwig-0.2.1-py3.7.egg\ludwig\cli.py", line 64, in __init__
  File "C:\Users\sriki\Miniconda3\lib\site-packages\ludwig-0.2.1-py3.7.egg\ludwig\cli.py", line 94, in visualize
  File "C:\Users\sriki\Miniconda3\lib\site-packages\ludwig-0.2.1-py3.7.egg\ludwig\visualize.py", line 3119, in cli
  File "C:\Users\sriki\Miniconda3\lib\site-packages\ludwig-0.2.1-py3.7.egg\ludwig\visualize.py", line 650, in confusion_matrix_cli        
  File "C:\Users\sriki\Miniconda3\lib\site-packages\ludwig-0.2.1-py3.7.egg\ludwig\utils\data_utils.py", line 76, in load_json
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
but I have since figured out that I was not specifying the `ground_truth_metadata` option. The problems are:

1. The error message is not as informative as it can be.
2. It was not straightforward (at least for me) which of the files was the correct input to this option. I did eventually figure it was `test_set_metadata.json`. 

**Describe the use case**
The use case is a person reading the documentation and trying to use one of the visualizations. In my case it was confusion matrix, but it could be any of them.

**Describe the solution you'd like**
I think a walkthrough starting with a simple dataset would be quite helpful for a newcomer. Under visualization in user guide, start with this simple dataset. Then under each of the visualizations, after describing the CLI arguments, provide an example of how to use it.

**Describe alternatives you've considered**
Informative error messages are one way to go. For example, instead of the error I received above, something like:

```
You have not specified the ground_truth_metada argument for the confusion_matrix visualization.
```

**Additional context**
Again, this is probably an issue that only newcomers face, and is perhaps not that important for others. I am willing to help out if you think this is worth addressing.

**Comment by msaisumanth** [comment]
@sriki18 Thanks for raising the issue. A few other people also had issues around this recently. 

There a couple of things that can be done here:
1. Improve error messaging by doing sanity checks on the user inputs - ensure all the required arguments are provided
2. More detailed and complete examples for visualization.

We'll prioritize this with other pending tasks but feel free to create a pr for either one if you can.

**Comment by sriki18** [comment]
I can work on this. I will try out a bit of both and see which is more feasible for me. Wondering though, if you have pointers on how to go about it. Specifically, do you prefer something on every visualization in a single PR? Or something step by step? I just plan to start with training curves and confusion matrix for the moment...

**Comment by w4nderlust** [comment]
@sriki18 Thank you for being willing to help with this. You have to fork and then do a PR, what you do in your fork in terms of branches does not influence the forked repo. Having a PR for all visualizations would be ideal, but you can do a draft PR with just a subset of visualizations and we can discuss on that.

**Comment by sriki18** [comment]
Okay, thanks for the clarification! I will work on a draft and send you something in a few days.

**Comment by sriki18** [comment]
Updates: I started playing around with the Titanic dataset for illustrative purposes. I have `learning_cruves`, `confusion_matrix` and `compare_performance` working.

I am unable to get `compare_classifiers_performance_from_prob` working. I am trying the following:

```
ludwig visualize -v compare_classifiers_performance_from_prob --ground_truth train.csv --field Survived --probabilities results\titanic_Model1_0\Survived_probabilities.npy results\titanic_Model2_0\Survived_probabilities.npy -mn Model1 Model2
```

I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\username\Miniconda3\Scripts\ludwig-script.py", line 11, in <module>
    load_entry_point('ludwig==0.2.1', 'console_scripts', 'ludwig')()
  File "C:\Users\username\Miniconda3\lib\site-packages\ludwig-0.2.1-py3.7.egg\ludwig\cli.py", line 108, in main
  File "C:\Users\username\Miniconda3\lib\site-packages\ludwig-0.2.1-py3.7.egg\ludwig\cli.py", line 64, in __init__
  File "C:\Users\username\Miniconda3\lib\site-packages\ludwig-0.2.1-py3.7.egg\ludwig\cli.py", line 94, in visualize
  File "C:\Users\username\Miniconda3\lib\site-packages\ludwig-0.2.1-py3.7.egg\ludwig\visualize.py", line 3119, in cli
  File "C:\Users\username\Miniconda3\lib\site-packages\ludwig-0.2.1-py3.7.egg\ludwig\visualize.py", line 206, in compare_classifiers_performance_from_prob_cli
  File "C:\Users\username\Miniconda3\lib\site-packages\ludwig-0.2.1-py3.7.egg\ludwig\visualize.py", line 841, in compare_classifiers_performance_from_prob
  File "<__array_function__ internals>", line 6, in argsort
  File "C:\Users\username\Miniconda3\lib\site-packages\numpy\core\fromnumeric.py", line 1084, in argsort
    return _wrapfunc(a, 'argsort', axis=axis, kind=kind, order=order)
  File "C:\Users\username\Miniconda3\lib\site-packages\numpy\core\fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
numpy.AxisError: axis 1 is out of bounds for array of dimension 1
```

When I feed in the probability csv files with 

```
ludwig visualize -v compare_classifiers_performance_from_prob --ground_truth train.csv --field Survived --probabilities results\titanic_Model1_0\Survived_probabilities.csv results\titanic_Model2_0\Survived_probabilities.csv -mn Model1 Model2
```
I get

```
Traceback (most recent call last):
  File "C:\Users\username\Miniconda3\Scripts\ludwig-script.py", line 11, in <module>
    load_entry_point('ludwig==0.2.1', 'console_scripts', 'ludwig')()
  File "C:\Users\username\Miniconda3\lib\site-packages\ludwig-0.2.1-py3.7.egg\ludwig\cli.py", line 108, in main
  File "C:\Users\username\Miniconda3\lib\site-packages\ludwig-0.2.1-py3.7.egg\ludwig\cli.py", line 64, in __init__
  File "C:\Users\username\Miniconda3\lib\site-packages\ludwig-0.2.1-py3.7.egg\ludwig\cli.py", line 94, in visualize
  File "C:\Users\username\Miniconda3\lib\site-packages\ludwig-0.2.1-py3.7.egg\ludwig\visualize.py", line 3119, in cli
  File "C:\Users\username\Miniconda3\lib\site-packages\ludwig-0.2.1-py3.7.egg\ludwig\visualize.py", line 206, in compare_classifiers_performance_from_prob_cli
  File "C:\Users\username\Miniconda3\lib\site-packages\ludwig-0.2.1-py3.7.egg\ludwig\visualize.py", line 845, in compare_classifiers_performance_from_prob
AttributeError: 'bool' object has no attribute 'sum'
```

Am I feeding in the wrong `ground_truth` file?

Attaching the training file, model files and training commands for convenience.

```
ludwig experiment --experiment_name titanic --model_name Model1 --data_csv train.csv -mdf titanic_model1.yaml
ludwig experiment --experiment_name titanic --model_name Model2 --data_csv train.csv -mdf titanic_model2.yaml
ludwig visualize -v compare_performance -mn Model1 Model2 --test_statistics results\titanic_Model1_0\test_statistics.json results\titanic_Model2_0\test_statistics.json --field Survived
```
[train_and_models.zip](https://github.com/uber/ludwig/files/3506647/train_and_models.zip)

**Comment by sriki18** [comment]
@w4nderlust I got a hang of the plotting. I was testing it out with the Titanic dataset, but it has only 2 classes. I think explanation would be better with a multi-class dataset. Do you have a dataset in mind? 

- Current plots in the User guide use an airline dataset, but I am not familiar with it
- Current multi-class in the Examples section of the documentation is an image classification problem. I should like a simpler dataset (numerical/categorical features, fast training), if possible.
- If not, I will try some very simple CNNs for the fashion MNIST. I think the dataset is easy enough to understand and class names are clear.

**Comment by w4nderlust** [comment]
As I had to do some other changes, I took your example commands and pasted into another commit I was doing. Anyway, thank you for your PR!
