### ISSUE TITLE
error ludwig after install tensorflow-gpu

### ISSUE THREAD

**Issue by sbrfarhadi** [uber/ludwig#504]
I installed ludwig in a virtualenv with last github master code and start successfuly train with CPU.
I have decided to install the GPU with the following command

pip uninstall tensorflow
pip install tensorflow-gpu

install completed But after run ludwig show the following error 

(venv) D:\Project\*****\virtualenv\ludwig-master-gpu>ludwig

Traceback (most recent call last):
  File "D:\Project\*****\virtualenv\ludwig-master\venv\Scripts\ludwig-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "D:\Project\*****\virtualenv\ludwig-master\venv\lib\site-packages\pkg_resources\__init__.py", line 3250, in <module>
    @_call_aside
  File "D:\Project\*****\virtualenv\ludwig-master\venv\lib\site-packages\pkg_resources\__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "D:\Project\*****\virtualenv\ludwig-master\venv\lib\site-packages\pkg_resources\__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "D:\Project\*****\virtualenv\ludwig-master\venv\lib\site-packages\pkg_resources\__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "D:\Project\*****\virtualenv\ludwig-master\venv\lib\site-packages\pkg_resources\__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "D:\Project\*****\virtualenv\ludwig-master\venv\lib\site-packages\pkg_resources\__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)

pkg_resources.DistributionNotFound: The 'tensorflow==1.14.0' distribution was not found and is required by ludwig

**Comment by sbrfarhadi** [comment]
1.14.0

![image](https://user-images.githubusercontent.com/24922779/63756035-ef965080-c8cc-11e9-8916-cf6ff56b506d.png)

**Comment by sbrfarhadi** [comment]
thanks
i removed env and installed it again of github last source and change requirements.txt replace tensorflow with tensorflow-gpu
