### ISSUE TITLE
Use case example for seq2seq does not work

### ISSUE THREAD

**Issue by niedakh** [uber/ludwig#540]
I have a csv with two columns: paragraph and text, and the following model definition based on the user guide:

```yaml
input_features:
    -
        name: paragraph
        type: text
        level: word
        encoder: rnn
        cell_type: lstm
        reduce_output: null

output_features:
    -
        name: text
        type: text
        level: word
        decoder: generator
        cell_type: lstm
        attention: bahdanau
        loss:
            type: sampled_softmax_cross_entropy

training:
    batch_size: 96
```

Running:
```
ludwig train --data_train_csv ./20191018_seq2seq_train.csv  --data_test_csv ./20191018_seq2seq_test.csv --model_definition_file model_definition_seq2seq.yaml 
``` 
causes this configuration fails with the following error:

```
Traceback (most recent call last):
  File "/home/aci-user/venv36/bin/ludwig", line 11, in <module>
    sys.exit(main())
  File "/home/aci-user/venv36/lib64/python3.6/site-packages/ludwig/cli.py", line 108, in main
    CLI()
  File "/home/aci-user/venv36/lib64/python3.6/site-packages/ludwig/cli.py", line 64, in __init__
    getattr(self, args.command)()
  File "/home/aci-user/venv36/lib64/python3.6/site-packages/ludwig/cli.py", line 74, in train
    train.cli(sys.argv[2:])
  File "/home/aci-user/venv36/lib64/python3.6/site-packages/ludwig/train.py", line 785, in cli
    full_train(**vars(args))
  File "/home/aci-user/venv36/lib64/python3.6/site-packages/ludwig/train.py", line 336, in full_train
    debug=debug
  File "/home/aci-user/venv36/lib64/python3.6/site-packages/ludwig/train.py", line 483, in train
    debug=debug
  File "/home/aci-user/venv36/lib64/python3.6/site-packages/ludwig/models/model.py", line 113, in __init__
    **kwargs
  File "/home/aci-user/venv36/lib64/python3.6/site-packages/ludwig/models/model.py", line 187, in __build
    is_training=self.is_training
  File "/home/aci-user/venv36/lib64/python3.6/site-packages/ludwig/models/outputs.py", line 46, in build_outputs
    **kwargs
  File "/home/aci-user/venv36/lib64/python3.6/site-packages/ludwig/models/outputs.py", line 96, in build_single_output
    **kwargs
  File "/home/aci-user/venv36/lib64/python3.6/site-packages/ludwig/features/base_feature.py", line 314, in concat_dependencies_and_build_output
    **kwargs
  File "/home/aci-user/venv36/lib64/python3.6/site-packages/ludwig/features/text_feature.py", line 291, in build_output
    kwarg=kwargs
  File "/home/aci-user/venv36/lib64/python3.6/site-packages/ludwig/features/sequence_feature.py", line 314, in build_sequence_output
    class_biases
  File "/home/aci-user/venv36/lib64/python3.6/site-packages/ludwig/features/sequence_feature.py", line 529, in sequence_loss
    self.num_classes
  File "/home/aci-user/venv36/lib64/python3.6/site-packages/ludwig/models/modules/loss_modules.py", line 239, in sequence_sampled_softmax_cross_entropy
    raise ValueError('Unsupported sampler {}'.format(loss['sampler']))
ValueError: Unsupported sampler None
```

**Comment by w4nderlust** [comment]
The commit should solve the problem, please install from master and confirm. 
`pip uninstall ludwig && pip install git+http://github.com/uber/ludwig.git`
