### ISSUE TITLE
KeyError when using text features

### ISSUE THREAD

**Issue by sk-** [uber/ludwig#56]
When using text features, the following error is raised:

```
Traceback (most recent call last):
  File "/Users/user/.virtualenvs/ml/bin/ludwig", line 10, in <module>
    sys.exit(main())
  File "/Users/user/.virtualenvs/ml/lib/python3.6/site-packages/ludwig/cli.py", line 86, in main
    CLI()
  File "/Users/user/.virtualenvs/ml/lib/python3.6/site-packages/ludwig/cli.py", line 64, in __init__
    getattr(self, args.command)()
  File "/Users/user/.virtualenvs/ml/lib/python3.6/site-packages/ludwig/cli.py", line 70, in train
    train.cli(sys.argv[2:])
  File "/Users/user/.virtualenvs/ml/lib/python3.6/site-packages/ludwig/train.py", line 663, in cli
    full_train(**vars(args))
  File "/Users/user/.virtualenvs/ml/lib/python3.6/site-packages/ludwig/train.py", line 224, in full_train
    random_seed=random_seed
  File "/Users/user/.virtualenvs/ml/lib/python3.6/site-packages/ludwig/data/preprocessing.py", line 562, in preprocess_for_training
    [training_set, validation_set, test_set]
  File "/Users/user/.virtualenvs/ml/lib/python3.6/site-packages/ludwig/data/preprocessing.py", line 777, in replace_text_feature_level
    level)
KeyError: 'name_word'
```

This is due to the following lines https://github.com/uber/ludwig/blob/9de6ee32f0e2e6cc6157f0772aa8c28a8d662fe8/ludwig/data/preprocessing.py#L774-L778 as it removes the columns regarding of whether they exist or not. Conditionally removing the columns fixes the issue and the model trains successfully.

The model definition I'm using is:
```yaml
input_features:
    -
        name: name
        type: text
        encoder: rnn
        level: char

output_features:
    -
        name: sex
        type: category
```

**Comment by w4nderlust** [comment]
The latest commit should fix it. Please confirm and I'll close the issue.

**Comment by sk-** [comment]
Thanks @w4nderlust for the quick fix. I confirm that works.

**Comment by w4nderlust** [comment]
You're welcome!
