### ISSUE TITLE
ludwig fails to work with uppercase extension names such as CSV and JSON

### ISSUE THREAD

**Issue by vood** [uber/ludwig#64]
On my Mac I'm trying to use a file with a .CSV extension such as input.CSV. Unfortunately, ludwig fails to load such files in preprocessing since string.replace in python is case sensitive. 

Steps to reproduce (provided you already have a trained model):
1. Create your prediction data csv file and name it `prediction.CSV`
2. Execute command ```ludwig predict --data_csv prediction.CSV --model_path results/experiment_run_0/model```

Expected behavior:
ludwig can read the file

Actual:
An exception is thrown:

``` _         _        _
| |_  _ __| |_ __ _(_)__ _
| | || / _` \ V  V / / _` |
|_|\_,_\__,_|\_/\_/|_\__, |
                     |___/
ludwig v0.1.0 - Predict

Dataset type: generic
Dataset path: prediction.CSV
Model path: results/experiment_run_0/model
Output path: results_0

Found hdf5 with the same filename of the csv, using it instead
Loading metadata from: results/experiment_run_0/model/train_set_metadata.json
Loading data from: prediction.CSV
Traceback (most recent call last):
  File "/Users/vood/.pyenv/versions/3.6.3/bin/ludwig", line 11, in <module>
    sys.exit(main())
  File "/Users/vood/.pyenv/versions/3.6.3/lib/python3.6/site-packages/ludwig/cli.py", line 86, in main
    CLI()
  File "/Users/vood/.pyenv/versions/3.6.3/lib/python3.6/site-packages/ludwig/cli.py", line 64, in __init__
    getattr(self, args.command)()
  File "/Users/vood/.pyenv/versions/3.6.3/lib/python3.6/site-packages/ludwig/cli.py", line 73, in predict
    predict.cli(sys.argv[2:])
  File "/Users/vood/.pyenv/versions/3.6.3/lib/python3.6/site-packages/ludwig/predict.py", line 379, in cli
    full_predict(**vars(args))
  File "/Users/vood/.pyenv/versions/3.6.3/lib/python3.6/site-packages/ludwig/predict.py", line 86, in full_predict
    only_predictions
  File "/Users/vood/.pyenv/versions/3.6.3/lib/python3.6/site-packages/ludwig/data/preprocessing.py", line 660, in preprocess_for_prediction
    shuffle_training=False
  File "/Users/vood/.pyenv/versions/3.6.3/lib/python3.6/site-packages/ludwig/data/preprocessing.py", line 239, in load_data
    hdf5_data = h5py.File(hdf5_file_path, 'r')
  File "/Users/vood/.pyenv/versions/3.6.3/lib/python3.6/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/Users/vood/.pyenv/versions/3.6.3/lib/python3.6/site-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (file signature not found)```

**Comment by w4nderlust** [comment]
Thanks for sending this!
This is a small fix, will do it tomorrow.
