### ISSUE TITLE
Error initialising wandb using the --wandb flag with the CLI

### ISSUE THREAD

**Issue by danielduckworth** [uber/ludwig#656]
**Describe the bug**
I'm trying to use the --wandb flag with the CLI using Google Colab.

First I log in to wandb:

!wandb login [hash]

Then I define the wandb project:

import wandb
wandb.init(project="isa-short-answer-scoring")

Then I run ludwig cli with the wandb flag.

!ludwig experiment --data_csv "file.csv" --model_definition_file "definition.yaml" --wandb

The error is below:

wandb.train_init() called...
Traceback (most recent call last):
  File "/usr/local/bin/ludwig", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/ludwig/cli.py", line 118, in main
    CLI()
  File "/usr/local/lib/python3.6/dist-packages/ludwig/cli.py", line 64, in __init__
    getattr(self, args.command)()
  File "/usr/local/lib/python3.6/dist-packages/ludwig/cli.py", line 69, in experiment
    experiment.cli(sys.argv[2:])
  File "/usr/local/lib/python3.6/dist-packages/ludwig/experiment.py", line 842, in cli
    full_experiment(**vars(args))
  File "/usr/local/lib/python3.6/dist-packages/ludwig/experiment.py", line 350, in full_experiment
    **kwargs
  File "/usr/local/lib/python3.6/dist-packages/ludwig/experiment.py", line 125, in experiment
    **kwargs
  File "/usr/local/lib/python3.6/dist-packages/ludwig/train.py", line 337, in full_train
    resume=model_resume_path is not None)
  File "/usr/local/lib/python3.6/dist-packages/ludwig/contrib.py", line 65, in contrib_command
    method(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ludwig/contribs/wandb.py", line 57, in train_init
    wandb.save(os.path.join(experiment_directory, "*"))
  File "/usr/local/lib/python3.6/dist-packages/wandb/__init__.py", line 563, in save
    "You must call `wandb.init` before calling save")
ValueError: You must call `wandb.init` before calling save

**To Reproduce**
training:
 dropout_rate: 0.2
 epochs: 50

input_features:
-
 name: text
 type: text
 encoder: rnn
 pretrained_embeddings: glove.6B.300d.txt
 embedding_size: 300
 cell_type: lstm_cudnn
 bidirectional: true
 dropout: true

output_features:
-
 name: score
 type: category

**Expected behavior**
Run training and log data to wandb

**Environment (please complete the following information):**
 - OS: Google Colab
- Python version: 3.6
- Ludwig version: 0.2.2.1

**Comment by danielduckworth** [comment]
I figured out the issue. I don't need to initialise the wandb project separately from the ludwig CLI run.

**Comment by w4nderlust** [comment]
Glad you solved it!
