### ISSUE TITLE
Issue With Predictions from API

### ISSUE THREAD

**Issue by FellCrustacean8** [uber/ludwig#683]
When running the trained model I get the following error
```
Traceback (most recent call last):
  File "predict.py", line 3, in <module>
    x = model.predict({"numberIn":[1]}, return_type='dict')
  File "/home/user/.local/lib/python3.7/site-packages/ludwig/api.py", line 914, in predict
    gpu_fraction=gpu_fraction,
  File "/home/user/.local/lib/python3.7/site-packages/ludwig/api.py", line 772, in _predict
    self.model_definition['preprocessing']
  File "/home/user/.local/lib/python3.7/site-packages/ludwig/data/preprocessing.py", line 159, in build_data
    preprocessing_parameters
  File "/home/user/.local/lib/python3.7/site-packages/ludwig/data/preprocessing.py", line 180, in handle_missing_values
    dataset_df[feature['name']] = dataset_df[feature['name']].fillna(
AttributeError: 'list' object has no attribute 'fillna'
```

I'm giving input data through a dictionary. Here is the prediction script
```
from ludwig.api import LudwigModel
model = LudwigModel.load("/home/user/Documents/ludwig-test/plus1/results/api_experiment_run_0/model")
x = model.predict({"numberIn":[1]}, return_type='dict')
#x = model.predict({"numberIn":[1]}, return_type=<class 'dict'>) I tried this with no success
print(x)
```

Training Script
```
mydata = {"numberIn":[], "value":[]}

for x in range(10000):
    mydata["numberIn"].append(x)
    mydata["value"].append(x + 1)

from ludwig.api import LudwigModel
print("Imported Ludwig")
modelobject = LudwigModel(model_definition_file="modeldef.yaml")
stats = modelobject.train(data_dict=mydata)
modelobject.close()
```

Modeldef file
```
input_features:
    -
        name: numberIn
        type: numerical

output_features:
    -
        name: value
        type: numerical
```

**Comment by FellCrustacean8** [comment]
Just after writing this post it finally hit me. I forgot to specify argument name. Sorry about this post, I got stuck on the issue for a day and a half.

**Comment by w4nderlust** [comment]
This is useful info anyway, it means that te docs or the mecanism for fetermining the input to the predict function are not super clear, will work on it. Glad you solved it anyway,
