### ISSUE TITLE
ImportError: cannot import name '_validate_lengths'

### ISSUE THREAD

**Issue by jiangweiatgithub** [uber/ludwig#72]
E:\repos\tensorflow>pushd E:\repos\tensorflow

E:\repos\tensorflow>ludwig experiment --data_csv translation.csv --model_definition_file model_definition.yaml
e:\programdata\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "e:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\ProgramData\Anaconda3\Scripts\ludwig.exe\__main__.py", line 5, in <module>
  File "e:\programdata\anaconda3\lib\site-packages\ludwig\__init__.py", line 16, in <module>
    from ludwig.api import LudwigModel
  File "e:\programdata\anaconda3\lib\site-packages\ludwig\api.py", line 39, in <module>
    from ludwig.data.postprocessing import postprocess_df, postprocess
  File "e:\programdata\anaconda3\lib\site-packages\ludwig\data\postprocessing.py", line 19, in <module>
    from ludwig.features.feature_registries import output_type_registry
  File "e:\programdata\anaconda3\lib\site-packages\ludwig\features\feature_registries.py", line 33, in <module>
    from ludwig.features.image_feature import ImageBaseFeature
  File "e:\programdata\anaconda3\lib\site-packages\ludwig\features\image_feature.py", line 24, in <module>
    from skimage.io import imread
  File "e:\programdata\anaconda3\lib\site-packages\skimage\__init__.py", line 158, in <module>
    from .util.dtype import *
  File "e:\programdata\anaconda3\lib\site-packages\skimage\util\__init__.py", line 7, in <module>
    from .arraycrop import crop
  File "e:\programdata\anaconda3\lib\site-packages\skimage\util\arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name '_validate_lengths'

**Comment by hemchander23** [comment]
Had similar errors. It was gone after I updated the respective packages.

<pre>
pip install -U numpy
pip install -U scikit-image
</pre>

**Comment by jiangweiatgithub** [comment]
What is your numpy version? I got the follow when I tried updating it:
pip install -U numpy
Requirement already up-to-date: numpy in e:\programdata\anaconda3\lib\site-packages (1.16.1)

**Comment by hemchander23** [comment]
From what I see, you have the latest version(mine is 1.16.1 as well).. Can you run 
```python setup.py install``` & access ludwig again ? In my case, the error disappeared after I updated those two packages.

**Comment by jiangweiatgithub** [comment]
Yes, now THAT issue has disappeared, but a new issue has popped up. I will post soon.

**Comment by athlonshi** [comment]
scikit-image 0.14.2 and numpy 1.16.1 should work
You may need to restart python environment after the update

**Comment by w4nderlust** [comment]
@jiangweiatgithub closing this, if you have another issue please open another one.
