### ISSUE TITLE
Subprocess does not find git on Windows 

### ISSUE THREAD

**Issue by ksteinfe** [uber/ludwig#74]
Upon first running, I get the error below. I traced this back to a problem with the way in which Windows resolves executable extensions, per the links below. I am able to resolve this for now by adding the shell=True argument to line 41 of ludwig\utils\misc.py, but this solution is not recommended. Any advice? 

I am running Anaconda on Windows 10. Github Desktop and Git for Windows installed.

- https://github.com/kennethreitz/legit/issues/148
- https://stackoverflow.com/questions/4965175/make-subprocess-find-git-executable-on-windows/10555130#10555130

> the Windows API function CreateProcess, used by subprocess under the hood, doesn't auto-resolve other executable extensions than .exe. On Windows, the 'git' command is really installed as git.cmd. Therefore, you should modify your example to explicitly invoke git.cmd

Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\ludwig.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\lib\site-packages\ludwig\cli.py", line 86, in main
    CLI()
  File "c:\anaconda3\lib\site-packages\ludwig\cli.py", line 64, in __init__
    getattr(self, args.command)()
  File "c:\anaconda3\lib\site-packages\ludwig\cli.py", line 67, in experiment
    experiment.cli(sys.argv[2:])
  File "c:\anaconda3\lib\site-packages\ludwig\experiment.py", line 548, in cli
    experiment(**vars(args))
  File "c:\anaconda3\lib\site-packages\ludwig\experiment.py", line 201, in experiment
    random_seed
  File "c:\anaconda3\lib\site-packages\ludwig\utils\misc.py", line 43, in get_experiment_description
    stdout=open(os.devnull, 'w')) == 0
  File "c:\anaconda3\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "c:\anaconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by w4nderlust** [comment]
That functionality is useful to keep track of the specific git hash of the current Ludwig directory if you are running experiments from a cloned repo. it is not a feature everyone will use, so I'll probably just wrap it in a try/except and return `False` otherwise. Will look into it and see if I can find a better solution, but the problem is that i don't have a windows machine to test it on at the moment, will have to create a virtual machine specifically for this purpose. Anyway, with that fix in the meantime it will make it usable for Windows users at least.

**Comment by ksteinfe** [comment]
Yes, that fixes the issue.
Thank you!
