### ISSUE TITLE
install error on windows

### ISSUE THREAD

**Issue by alain2208** [uber/ludwig#77]
HI using py 3.6 under windows 10 with tensorflow or tensorflow gpu got this message
i installed it yesterday on another windows machine no problem but failed on my personal one
failed with the version of this evening #74 i think
btw great job!

same thing if i try in import ludwg under jupyter notebook

D:\>ludwig
Traceback (most recent call last):
  File "d:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\Anaconda3\Scripts\ludwig.exe\__main__.py", line 5, in <module>
  File "d:\anaconda3\lib\site-packages\ludwig\__init__.py", line 16, in <module>
    from ludwig.api import LudwigModel
  File "d:\anaconda3\lib\site-packages\ludwig\api.py", line 38, in <module>
    from ludwig.data.dataset import Dataset
  File "d:\anaconda3\lib\site-packages\ludwig\data\dataset.py", line 17, in <module>
    import h5py
  File "d:\anaconda3\lib\site-packages\h5py\__init__.py", line 26, in <module>
    from . import _errors
ImportError: cannot import name '_errors'

**Comment by w4nderlust** [comment]
Thanks @alain2208 ! it looks like your anaconda is missing h5py, can you try to install it and retry please?

**Comment by alain2208** [comment]
it was not missing but in 2.7.1 after upgrade 2.9.0 no more this error ,  but another related to timeseriers >>> import ludwig
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\Anaconda3\lib\site-packages\ludwig\__init__.py", line 16, in <module>
    from ludwig.api import LudwigModel
  File "d:\Anaconda3\lib\site-packages\ludwig\api.py", line 39, in <module>
    from ludwig.data.postprocessing import postprocess_df, postprocess
  File "d:\Anaconda3\lib\site-packages\ludwig\data\postprocessing.py", line 19, in <module>
    from ludwig.features.feature_registries import output_type_registry
  File "d:\Anaconda3\lib\site-packages\ludwig\features\feature_registries.py", line 25, in <module>
    from ludwig.features.bag_feature import BagBaseFeature
  File "d:\Anaconda3\lib\site-packages\ludwig\features\bag_feature.py", line 24, in <module>
    from ludwig.features.base_feature import BaseFeature
  File "d:\Anaconda3\lib\site-packages\ludwig\features\base_feature.py", line 21, in <module>
    from ludwig.models.modules.recurrent_modules import reduce_sequence
  File "d:\Anaconda3\lib\site-packages\ludwig\models\modules\recurrent_modules.py", line 20, in <module>
    from tensorflow.contrib.rnn import MultiRNNCell, LSTMStateTuple
  File "d:\Anaconda3\lib\site-packages\tensorflow\contrib\__init__.py", line 98, in <module>
    from tensorflow.contrib import timeseries
  File "d:\Anaconda3\lib\site-packages\tensorflow\contrib\timeseries\__init__.py", line 40, in <module>
    from tensorflow.contrib.timeseries.python.timeseries import *
  File "d:\Anaconda3\lib\site-packages\tensorflow\contrib\timeseries\python\__init__.py", line 22, in <module>
    from tensorflow.contrib.timeseries.python.timeseries import *
  File "d:\Anaconda3\lib\site-packages\tensorflow\contrib\timeseries\python\timeseries\__init__.py", line 21, in <module
>
    from tensorflow.contrib.timeseries.python.timeseries import saved_model_utils
  File "d:\Anaconda3\lib\site-packages\tensorflow\contrib\timeseries\python\timeseries\saved_model_utils.py", line 28, i
n <module>
    from tensorflow.contrib.timeseries.python.timeseries import input_pipeline as _input_pipeline
  File "d:\Anaconda3\lib\site-packages\tensorflow\contrib\timeseries\python\timeseries\input_pipeline.py", line 423, in
<module>
    class CSVReader(ReaderBaseTimeSeriesParser):
  File "d:\Anaconda3\lib\site-packages\tensorflow\contrib\timeseries\python\timeseries\input_pipeline.py", line 428, in
CSVReader
    column_names=(feature_keys.TrainEvalFeatures.TIMES,
AttributeError: module 'tensorflow.contrib.timeseries.python.timeseries.feature_keys' has no attribute 'TrainEvalFeature
s'
>>>

**Comment by w4nderlust** [comment]
Sorry i have a hard time understanding the stacktrace without clear indentation and a frame of reference.
Can you please provide a reproducible example?

**Comment by alain2208** [comment]
I just open python intepreter and type import ludwig or i launch an experiment from the command lines with good parameters. Will ty to do more clean stack trace

**Comment by w4nderlust** [comment]
What version of TensorFlow have you installed? It looks like there is one import from TensorFlow that does not work, which is likely because of a version mismatch. Please try to use `tesnorflow=1.12` and let me know if that solves the issue.

**Comment by alain2208** [comment]
the problem was double tensorflow install both tensorflow and tensorflow gpu was installed. I also had some other dependencies missing now it solved

**Comment by alain2208** [comment]
solved by myslef

**Comment by satwi95** [comment]
Can i install ludwig on windows ? and can i write in spyder

**Comment by w4nderlust** [comment]
@satwi95 I don't have a windows machine so I cannot test it, but in theory there should be nothing stopping you from doing both.
