### ISSUE TITLE
Latest master (TF2) dropout on RNN is broken

### ISSUE THREAD

**Issue by carlogrisetti** [uber/ludwig#823]
Issue presents with this input feature combination
Feature type: timeseries
Encoder: rnn
Dropout: true

It's correctly working with these two input feature combinations
Feature type: timeseries
Encoder: rnn
Dropout: false

Feature type: timeseries
Encoder: stacked_cnn
Dropout: true

(thus it seems to be related to rnn+dropout)
Here it is the stack trace:

Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\Scripts\ludwig.exe\__main__.py", line 7, in <module>
  File "c:\program files\python36\lib\site-packages\ludwig\cli.py", line 125, in main
    CLI()
  File "c:\program files\python36\lib\site-packages\ludwig\cli.py", line 66, in __init__
    getattr(self, args.command)()
  File "c:\program files\python36\lib\site-packages\ludwig\cli.py", line 76, in train
    train.cli(sys.argv[2:])
  File "c:\program files\python36\lib\site-packages\ludwig\train.py", line 825, in cli
    full_train(**vars(args))
  File "c:\program files\python36\lib\site-packages\ludwig\train.py", line 361, in full_train
    debug=debug
  File "c:\program files\python36\lib\site-packages\ludwig\train.py", line 532, in train
    **model_definition[TRAINING]
  File "c:\program files\python36\lib\site-packages\ludwig\models\trainer.py", line 483, in train
    regularization_lambda
  File "c:\program files\python36\lib\site-packages\tensorflow\python\eager\def_function.py", line 564, in __call__
    return self._python_function(*args, **kwds)
  File "c:\program files\python36\lib\site-packages\tensorflow\python\eager\function.py", line 3294, in bound_method_wrapper
    return wrapped_fn(weak_instance(), *args, **kwargs)
  File "c:\program files\python36\lib\site-packages\ludwig\models\ecd.py", line 152, in train_step
    logits = self((inputs, targets), training=True)
  File "c:\program files\python36\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 968, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "c:\program files\python36\lib\site-packages\tensorflow\python\eager\def_function.py", line 564, in __call__
    return self._python_function(*args, **kwds)
  File "c:\program files\python36\lib\site-packages\tensorflow\python\eager\function.py", line 3294, in bound_method_wrapper
    return wrapped_fn(weak_instance(), *args, **kwargs)
  File "c:\program files\python36\lib\site-packages\ludwig\models\ecd.py", line 71, in call
    mask=mask)
  File "c:\program files\python36\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 968, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "c:\program files\python36\lib\site-packages\ludwig\features\timeseries_feature.py", line 142, in call
    inputs_exp, training=training, mask=mask
  File "c:\program files\python36\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 968, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "c:\program files\python36\lib\site-packages\ludwig\encoders\sequence_encoders.py", line 1491, in call
    mask=mask
  File "c:\program files\python36\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 968, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "c:\program files\python36\lib\site-packages\ludwig\modules\recurrent_modules.py", line 103, in call
    outputs = layer(hidden, training=training, mask=mask)
  File "c:\program files\python36\lib\site-packages\tensorflow\python\keras\layers\recurrent.py", line 654, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "c:\program files\python36\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 968, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "c:\program files\python36\lib\site-packages\tensorflow\python\keras\layers\recurrent_v2.py", line 1147, in call
    dropout_mask = self.get_dropout_mask_for_cell(inputs, training, count=4)
  File "c:\program files\python36\lib\site-packages\tensorflow\python\keras\layers\recurrent.py", line 1156, in get_dropout_mask_for_cell
    return self._dropout_mask_cache.setdefault(kwargs=init_kwargs)
  File "c:\program files\python36\lib\site-packages\tensorflow\python\keras\backend.py", line 6180, in setdefault
    default = self.default_factory(**kwargs)
  File "c:\program files\python36\lib\site-packages\tensorflow\python\keras\layers\recurrent.py", line 1128, in _create_dropout_mask
    count=count)
  File "c:\program files\python36\lib\site-packages\tensorflow\python\keras\layers\recurrent.py", line 2850, in _generate_dropout_mask
    for _ in range(count)
  File "c:\program files\python36\lib\site-packages\tensorflow\python\keras\layers\recurrent.py", line 2850, in <listcomp>
    for _ in range(count)
  File "c:\program files\python36\lib\site-packages\tensorflow\python\keras\backend.py", line 4361, in in_train_phase
    return x()
  File "c:\program files\python36\lib\site-packages\tensorflow\python\keras\layers\recurrent.py", line 2845, in dropped_inputs
    return K.dropout(ones, rate)
  File "c:\program files\python36\lib\site-packages\tensorflow\python\keras\backend.py", line 4768, in dropout
    return nn.dropout_v2(x, rate=level, noise_shape=noise_shape, seed=seed)
  File "c:\program files\python36\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 4423, in dropout_v2
    "range [0, 1), got %g" % rate)
ValueError: rate must be a scalar tensor or a float in the range [0, 1), got 1

**Comment by carlogrisetti** [comment]
This also happens with different cell types within the RNN encoder, and also happens with CNNRNN encoder, and also does *NOT* happen with parallel_cnn (other than already it does not happen with stacked_cnn)

**Comment by w4nderlust** [comment]
The dropout logic is different in v0.3 (the user guide does not reflact this yet).
Now instead of a single float `dropout` parameter in `training` and several binary `dropout` parameters in the encoder/combiner/decoder you have a `dropout_rate` parameter in each encoder/combiner/decoder.

Try replacing `dropout: true` with `dropout_rate: 0.x`.

**Comment by carlogrisetti** [comment]
Well... In this case is reversely broken, since with all the other encoders it still accepts dropout: true without a flinch :)

Sorry for that misunderstanding... Now that you say that I remember discussing this in a previous instance

**Comment by w4nderlust** [comment]
Upon inspection, it looks like Redurrent stack indeed uses dropout instead of dropout_rate. 
All other encoders just ignore the parameters, but the recurrent one actually uses it and expects it to be a float between 0 and 1.

So this suggests a couple actions:
- produce a warning when a parameter passed to an encoder is ignored (which would have given you insight on what's happening)
- use the same name across different encoders (either dropout or dropout_rate

Also, consider the current code on master is an alpha version (v0.3-a1), so it's actually great that you are playing with it and helping us figure out bugs before release, thank you! ;)

**Comment by carlogrisetti** [comment]
...or either it should disregard the binary dropout flag as it does in the other encoders and not try to apply it like it seems to be doing.
It's almost like dropout didn't get renamed to dropout_rate and it's trying to apply the binary true (that I passed) to the float rate parameter it is expecting.

**Comment by w4nderlust** [comment]
Yes that's exactly what's happening. All others have dropout?rate, so dropout end in kwargs. This one actually has the dropout name instead of dropout_rate, but expects it to be within [0,1]. Now the `rnn` encoder has also a `recurrent_dropout` parameter ( look here for more details, now the exposed parameters match more closely those of TF2 layers 823 )
Will most likely rename everything dropout for simplicity.

**Comment by carlogrisetti** [comment]
Simultaneous :)

Yes I know it's an alpha, but since I'm starting the object detection/reading project I talked to you about, I didn't want to start it on an old framework and then be tied to that forever.
0.3.0 seems way more stable than I expected (I already got it all working from end to end, apart from that dropout thing, up to the actual inference embedded in the code) and I plan on keeping on this track for all projects from now on.

Happy it helps :)

**Comment by w4nderlust** [comment]
This commit solves the issue https://github.com/uber/ludwig/commit/5770df1fc77b85ffd153ccc9bdc17ea019839896 .
Now the parameter name is `dropout` and it's available in the different encoders/combiners/decoders and it's expected to be a float.

**Comment by carlogrisetti** [comment]
Fixed, but i think this is redundant now (and not used anymore), right?
https://github.com/uber/ludwig/blob/5770df1fc77b85ffd153ccc9bdc17ea019839896/ludwig/utils/defaults.py#L51

**Comment by w4nderlust** [comment]
Fixed that one too, thank you for noticing it.

**Comment by carlogrisetti** [comment]
Seen that :)
