### ISSUE TITLE
Image Captioning error

### ISSUE THREAD

**Issue by LiuSiT** [uber/ludwig#83]
Traceback (most recent call last):
  File "/Users/liusitong/lstworkspace/wowo-server/services/crawler_py/venv/bin/ludwig", line 11, in <module>
    sys.exit(main())
  File "/Users/liusitong/lstworkspace/wowo-server/services/crawler_py/venv/lib/python3.6/site-packages/ludwig/cli.py", line 86, in main
    CLI()
  File "/Users/liusitong/lstworkspace/wowo-server/services/crawler_py/venv/lib/python3.6/site-packages/ludwig/cli.py", line 64, in __init__
    getattr(self, args.command)()
  File "/Users/liusitong/lstworkspace/wowo-server/services/crawler_py/venv/lib/python3.6/site-packages/ludwig/cli.py", line 67, in experiment
    experiment.cli(sys.argv[2:])
  File "/Users/liusitong/lstworkspace/wowo-server/services/crawler_py/venv/lib/python3.6/site-packages/ludwig/experiment.py", line 548, in cli
    experiment(**vars(args))
  File "/Users/liusitong/lstworkspace/wowo-server/services/crawler_py/venv/lib/python3.6/site-packages/ludwig/experiment.py", line 258, in experiment
    debug=debug
  File "/Users/liusitong/lstworkspace/wowo-server/services/crawler_py/venv/lib/python3.6/site-packages/ludwig/train.py", line 368, in train
    debug=debug
  File "/Users/liusitong/lstworkspace/wowo-server/services/crawler_py/venv/lib/python3.6/site-packages/ludwig/models/model.py", line 110, in __init__
    **kwargs
  File "/Users/liusitong/lstworkspace/wowo-server/services/crawler_py/venv/lib/python3.6/site-packages/ludwig/models/model.py", line 184, in __build
    is_training=self.is_training
  File "/Users/liusitong/lstworkspace/wowo-server/services/crawler_py/venv/lib/python3.6/site-packages/ludwig/models/outputs.py", line 43, in build_outputs
    **kwargs
  File "/Users/liusitong/lstworkspace/wowo-server/services/crawler_py/venv/lib/python3.6/site-packages/ludwig/models/outputs.py", line 93, in build_single_output
    **kwargs
  File "/Users/liusitong/lstworkspace/wowo-server/services/crawler_py/venv/lib/python3.6/site-packages/ludwig/features/base_feature.py", line 314, in concat_dependencies_and_build_output
    **kwargs
  File "/Users/liusitong/lstworkspace/wowo-server/services/crawler_py/venv/lib/python3.6/site-packages/ludwig/features/sequence_feature.py", line 250, in build_output
    kwarg=kwargs
  File "/Users/liusitong/lstworkspace/wowo-server/services/crawler_py/venv/lib/python3.6/site-packages/ludwig/features/sequence_feature.py", line 320, in build_sequence_output
    eval_loss
  File "/Users/liusitong/lstworkspace/wowo-server/services/crawler_py/venv/lib/python3.6/site-packages/ludwig/features/sequence_feature.py", line 445, in sequence_measures
    self.name
  File "/Users/liusitong/lstworkspace/wowo-server/services/crawler_py/venv/lib/python3.6/site-packages/ludwig/models/modules/measure_modules.py", line 73, in masked_accuracy
    maxlen=correct_predictions.shape[1], dtype=tf.int32)
  File "/Users/liusitong/lstworkspace/wowo-server/services/crawler_py/venv/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 2504, in sequence_mask
    maxlen = ops.convert_to_tensor(maxlen)
  File "/Users/liusitong/lstworkspace/wowo-server/services/crawler_py/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1050, in convert_to_tensor
    as_ref=False)
  File "/Users/liusitong/lstworkspace/wowo-server/services/crawler_py/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/liusitong/lstworkspace/wowo-server/services/crawler_py/venv/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 282, in _dimension_tensor_conversion_function
    raise ValueError("Cannot convert an unknown Dimension to a Tensor: %s" % d)
ValueError: Cannot convert an unknown Dimension to a Tensor: ?

**Comment by msaisumanth** [comment]
Could you please provide more information like your model definition and the data format?

**Comment by LiuSiT** [comment]
![image](https://user-images.githubusercontent.com/27655640/52830540-126cce80-310c-11e9-99b3-44f70c792d24.png)
![image](https://user-images.githubusercontent.com/27655640/52830554-287a8f00-310c-11e9-9972-0dd5fdaace06.png)
![image](https://user-images.githubusercontent.com/27655640/52830575-4ba53e80-310c-11e9-8fcb-34809147ba09.png)
I follow this tutorial, the name does not follow the tutorial

**Comment by w4nderlust** [comment]
I tried to reproduce your error and I was not able to.
Let me ask you a couple questions:
- looking at your data, the caption column actually looks like it's a class id, have you considered using category as a datatype instead of sequence?
- if you were using a different ype doe the output features before, it may be the case that you created a hdf5 file and then you changed the type but kept on using the same hdf5. In this cases, deleting the hdf5 and json files with the same name of your csv in the same directory will let the model recreate them when you call train or experiment, and that should solve the problem
Let me know if either of those things solve your issue.

**Comment by LiuSiT** [comment]
![image](https://user-images.githubusercontent.com/27655640/52833579-58c82a80-3118-11e9-82f9-08e38455be60.png)
The example of classification can be used for normal training. My data verification code data. I think it's a better model for this example
![image](https://user-images.githubusercontent.com/27655640/52833666-d55b0900-3118-11e9-9630-7f19cae4ef34.png)

**Comment by w4nderlust** [comment]
I see. So you probably want to use `preprocessing: {format: characters}` in your decoder. But apart from it I can't see any problem with your model definition file and with your data, as when i try to replicate your issue it just runs fine. You can reach out to me privately with a sample of your data and i can try to help you out.

**Comment by MichaelSunEngineer** [comment]
@LiuSiT  hi I get the same problem, Did you solve the problem?

**Comment by w4nderlust** [comment]
@MichaelSunEngineer this works fine with the code on master for me. If you'd like me to try to give a shot at solving the issue, please provide a zip containing something we can replicate (yaml, csv sample, images sample).

**Comment by Knize** [comment]
Hello, i have close or same problem. I think i'm doing everything as in example.
![image](https://user-images.githubusercontent.com/9881948/55297091-01adb900-542b-11e9-8eb6-23661cb2695d.png)
Console output:
![image](https://user-images.githubusercontent.com/9881948/55297005-e0000200-5429-11e9-828d-c24b86985f94.png)
Csv, mdf, description.json, full  console output are in zip below:
[issueWithImageClassification.zip](https://github.com/uber/ludwig/files/3027334/issueWithImageClassification.zip)
.zip)

**Comment by w4nderlust** [comment]
@Knize There is a space before class in your csv.

**Comment by Knize** [comment]
@w4nderlust Thank you!

**Comment by FellCrustacean8** [comment]
I'm running into a similar issue. I tried some of the suggestions above with no success.
`/home/mark/.local/lib/python3.7/site-packages/h5py/_hl/dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  "Use dataset[()] instead.", H5pyDeprecationWarning)
Traceback (most recent call last):
  File "train.py", line 14, in <module>
    train_stats = model.train(data_csv="./dataset.csv")
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/api.py", line 441, in train
    debug=debug,
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/train.py", line 301, in full_train
    debug=debug
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/train.py", line 442, in train
    debug=debug
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/models/model.py", line 108, in __init__
    **kwargs
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/models/model.py", line 182, in __build
    is_training=self.is_training
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/models/outputs.py", line 43, in build_outputs
    **kwargs
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/models/outputs.py", line 93, in build_single_output
    **kwargs
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/features/base_feature.py", line 314, in concat_dependencies_and_build_output
    **kwargs
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/features/text_feature.py", line 266, in build_output
    kwarg=kwargs
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/features/sequence_feature.py", line 320, in build_sequence_output
    eval_loss
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/features/sequence_feature.py", line 445, in sequence_measures
    self.name
  File "/home/mark/.local/lib/python3.7/site-packages/ludwig/models/modules/measure_modules.py", line 73, in masked_accuracy
    maxlen=correct_predictions.shape[1], dtype=tf.int32)
  File "/home/mark/.local/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 3077, in sequence_mask
    maxlen = ops.convert_to_tensor(maxlen)
  File "/home/mark/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1039, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "/home/mark/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1097, in convert_to_tensor_v2
    as_ref=False)
  File "/home/mark/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1175, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/mark/.local/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 357, in _dimension_tensor_conversion_function
    raise ValueError("Cannot convert an unknown Dimension to a Tensor: %s" % d)
ValueError: Cannot convert an unknown Dimension to a Tensor: ?`

CSV Format
`image_path,plate
./crop_m1/I00000.png,9B52145
./crop_h1/I00000.png,9B52145
./crop_m1/I00001.png,6B94558
./crop_h1/I00001.png,6B94558
./crop_m1/I00002.png,8B90164
./crop_h1/I00002.png,8B90164
./crop_m1/I00003.png,5B11181
./crop_h1/I00003.png,5B11181
./crop_m1/I00004.png,8B79697
./crop_h1/I00004.png,8B79697
./crop_m1/I00005.png,8B90164
./crop_h1/I00005.png,8B90164
./crop_m1/I00006.png,5B11181
./crop_h1/I00006.png,5B11181
./crop_m1/I00007.png,5Z40181
./crop_h1/I00007.png,5Z40181
./crop_m1/I00008.png,2B20174
./crop_h1/I00008.png,2B20174
./crop_m1/I00009.png,1B76462
./crop_h1/I00009.png,1B76462
./crop_m1/I00010.png,BVJ6411
./crop_h1/I00010.png,BVJ6411
./crop_m1/I00011.png,8B79697
./crop_h1/I00011.png,8B79697
./crop_m1/I00012.png,BVJ6411
./crop_h1/I00012.png,BVJ6411
./crop_m1/I00013.png,1B94686
./crop_h1/I00013.png,1B94686`

Model Def in python script.
`from ludwig.api import LudwigModel

model_definition = {
    "input_features":[
        {"name":"image_path", "type":"image", "preprocessing":{"height": "128", "width": "128", "resize_method": "interpolate"}}
    ],
    "output_features":[
        {"name":"plate","type":"text"}
    ]
}

model = LudwigModel(model_definition)

train_stats = model.train(data_csv="./dataset.csv")
`

**Comment by vimagick** [comment]
There should be 6 output_features:

-----------------------------------

File: captcha.csv

```csv
img,c1,c2,c3,c4,c5,c6
captcha/YCXK76.png,Y,C,X,K,7,6
captcha/F587M4.png,F,5,8,7,M,4
captcha/6B68X3.png,6,B,6,8,X,3
```

File: captcha.yaml

```
input_features:
  - name: img
    type: image
    encoder: stacked_cnn
    preprocessing:
      num_channels: 1

output_features:
  - name: c1
    type: category
  - name: c2
    type: category
  - name: c3
    type: category
  - name: c4
    type: category
  - name: c5
    type: category
  - name: c6
    type: category
```

```bash
$ ludwig train --model_name captcha --data_csv captcha.csv -mdf captcha.yaml
```
