### ISSUE TITLE
utf-8 encoding error on text prediction

### ISSUE THREAD

**Issue by santsok** [uber/ludwig#90]
Hi, I'm getting the following stack trace when trying to do a simple prediction that should yield a text output containing utf-8 text, in this case the symbol ♋ .  I believe this comes down to csv.writer (in data_utils.py function save_csv) not playing nice with utf-8 out of the box.  I'm not super familiar with using python's native csv writing though.

```
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\Scripts\ludwig-script.py", line 11, in <module>
    load_entry_point('ludwig==0.1.0', 'console_scripts', 'ludwig')()
  File "c:\users\xxx\appdata\local\programs\python\python36\lib\site-packages\ludwig\cli.py", line 86, in main
    CLI()
  File "c:\users\xxxi\appdata\local\programs\python\python36\lib\site-packages\ludwig\cli.py", line 64, in __init__
    getattr(self, args.command)()
  File "c:\users\xxx\appdata\local\programs\python\python36\lib\site-packages\ludwig\cli.py", line 73, in predict
    predict.cli(sys.argv[2:])
  File "c:\users\xxx\appdata\local\programs\python\python36\lib\site-packages\ludwig\predict.py", line 379, in cli
    full_predict(**vars(args))
  File "c:\users\xxx\appdata\local\programs\python\python36\lib\site-packages\ludwig\predict.py", line 120, in full_predict
    save_prediction_outputs(postprocessed_output, experiment_dir_name)
  File "c:\users\xxx\appdata\local\programs\python\python36\lib\site-packages\ludwig\predict.py", line 210, in save_prediction_outputs
    save_csv(csv_filename.format(output_field, output_type), values)
  File "c:\users\xxx\appdata\local\programs\python\python36\lib\site-packages\ludwig\utils\data_utils.py", line 60, in save_csv
    writer.writerow(row)
  File "c:\users\xxx\appdata\local\programs\python\python36\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u264b' in position 0: character maps to <undefined>
```

**Comment by w4nderlust** [comment]
I pushed a commit that should fix the issue. Can you please confirm that the fix solves the issue?

**Comment by w4nderlust** [comment]
Closing the issue for now, feel free to reopen it if the fix doesn't solve your problem.
